creatures = [
    {"name": "A Greedy Eye", "exp": None, "hp": None},
    {"name": "A Shielded Astral Glyph", "exp": None, "hp": None},
    {"name": "A Weak Spot", "exp": None, "hp": None},
    {"name": "Abominable Spawn", "exp": None, "hp": None},
    {"name": "Abyssador", "exp": 50000, "hp": 340000},
    {"name": "Abyssal Calamary", "exp": 200, "hp": 300},
    {"name": "Achad", "exp": 70, "hp": 185},
    {"name": "Acid Blob", "exp": 250, "hp": 250},
    {"name": "Acolyte of Darkness", "exp": 200, "hp": 325},
    {"name": "Acolyte of the Cult", "exp": 300, "hp": 390},
    {"name": "Adept of the Cult", "exp": 400, "hp": 430},
    {"name": "Adult Goanna", "exp": 6650, "hp": 8300},
    {"name": "Adventurer", "exp": 0, "hp": 65},
    {"name": "Afflicted Strider", "exp": 5700, "hp": 10000},
    {"name": "Aftershock", "exp": None, "hp": None},
    {"name": "Aggressive Chicken", "exp": 0, "hp": 15000},
    {"name": "Aggressive Lava", "exp": None, "hp": None},
    {"name": "Aggressive Matter", "exp": 0, "hp": None},
    {"name": "Agrestic Chicken", "exp": 0, "hp": 15},
    {"name": "Alptramun", "exp": 55000, "hp": None},
    {"name": "Amarie", "exp": None,
     "hp": None},  # TODO: not working
    {"name": "Amazon", "exp": 60, "hp": 110},
    {"name": "Amenef the Burning", "exp": 21500, "hp": 26000},
    {"name": "An Astral Glyph", "exp": None, "hp": None},
    {"name": "An Observer Eye", "exp": 0, "hp": 30000},
    {"name": "Ancient Lion Archer", "exp": None, "hp": None},
    {"name": "Ancient Lion Knight", "exp": 8100, "hp": 9100},
    {"name": "Ancient Lion Warlock", "exp": None, "hp": None},
    {"name": "Ancient Scarab", "exp": 720, "hp": 1000},
    {"name": "Ancient Spawn of Morgathla", "exp": None, "hp": None},
    {"name": "Angry Adventurer", "exp": 50, "hp": 65},
    {"name": "Angry Demon", "exp": 6000, "hp": 8200},
    {"name": "Angry Elemental", "exp": 0, "hp": 7000},
    {"name": "Angry King Chuck", "exp": None, "hp": None},
    {"name": "Angry Plant", "exp": None, "hp": 10000},
    {"name": "Animated Clomp", "exp": 475, "hp": 900},
    {"name": "Animated Cyclops", "exp": 150, "hp": 260},
    {"name": "Animated Feather", "exp": 9860, "hp": 13000},
    {"name": "Animated Guzzlemaw", "exp": 5500, "hp": 6400},
    {"name": "Animated Moohtant", "exp": 2600, "hp": 3200},
    {"name": "Animated Mummy", "exp": 150, "hp": 240},
    {"name": "Animated Ogre Brute", "exp": 800, "hp": 1000},
    {"name": "Animated Ogre Savage", "exp": 950, "hp": 1400},
    {"name": "Animated Ogre Shaman", "exp": 625, "hp": 800},
    {"name": "Animated Rotworm", "exp": 40, "hp": 65},
    {"name": "Animated Skunk", "exp": None, "hp": None},
    {"name": "Animated Snowman", "exp": 400, "hp": 450},
    {"name": "Animated Sword", "exp": None, "hp": None},
    {"name": "Anmothra", "exp": 15000, "hp": 7000},
    {"name": "Annihilon", "exp": 15000, "hp": 46500},
    {"name": "Annoying Dog", "exp": None, "hp": None},
    {"name": "Anomaly", "exp": 50000, "hp": 290000},
    {"name": "Apprentice Sheng", "exp": 150, "hp": 95},
    {"name": "Arachir the Ancient One", "exp": 1800, "hp": 1600},
    {"name": "Arachnophobica", "exp": 4700, "hp": 5000},
    {"name": "Arctic Faun", "exp": 300, "hp": 300},
    {"name": "Armadile", "exp": 2900, "hp": 3800},
    {"name": "Armenius", "exp": 500, "hp": 550},
    {"name": "Arthei", "exp": 4000, "hp": 4200},
    {"name": "Arthom the Hunter", "exp": 550, "hp": 500},
    {"name": "Ascending Ferumbras", "exp": None, "hp": None},
    {"name": "Ashmunrah", "exp": 3100, "hp": 5000},
    {"name": "Askarak Demon", "exp": 900, "hp": 1500},
    {"name": "Askarak Lord", "exp": 1200, "hp": 2100},
    {"name": "Askarak Prince", "exp": 1700, "hp": 2600},
    {"name": "Aspect of Power", "exp": 0, "hp": 0},
    {"name": "Assassin", "exp": 105, "hp": 175},
    {"name": "Avalanche", "exp": 305, "hp": 550},
    {"name": "Axeitus Headbanger", "exp": 140, "hp": 365},
    {"name": "Azaram's Soul", "exp": 0, "hp": None},
    {"name": "Azerus", "exp": 6000, "hp": 26000},
    {"name": "Azure Frog", "exp": 20, "hp": 60},
    {"name": "Baby Dragon", "exp": None, "hp": None},
    {"name": "Bad Dream", "exp": None, "hp": None},
    {"name": "Bad Thought", "exp": 0, "hp": 500},
    {"name": "Badger", "exp": 5, "hp": 23},
    {"name": "Baleful Bunny", "exp": 450, "hp": 500},
    {"name": "Bandit", "exp": 65, "hp": 245},
    {"name": "Bane Bringer", "exp": 400, "hp": 2500},
    {"name": "Bane Lord", "exp": 500, "hp": 3000},
    {"name": "Bane of Light", "exp": 750, "hp": 1100},
    {"name": "Banshee", "exp": 900, "hp": 1000},
    {"name": "Barbaria", "exp": 355, "hp": 345},
    {"name": "Barbarian Bloodwalker", "exp": 195, "hp": 305},
    {"name": "Barbarian Brutetamer", "exp": 90, "hp": 145},
    {"name": "Barbarian Headsplitter", "exp": 85, "hp": 100},
    {"name": "Barbarian Skullhunter", "exp": 85, "hp": 135},
    {"name": "Barkless Devotee", "exp": 2200, "hp": 2800},
    {"name": "Barkless Fanatic", "exp": 2500, "hp": 3200},
    {"name": "Baron Brute", "exp": 3000, "hp": 5025},
    {"name": "Bashmu", "exp": 5000, "hp": 8200},
    {"name": "Bat", "exp": 10, "hp": 30},
    {"name": "Battlemaster Zunzu", "exp": 2500, "hp": 4000},
    {"name": "Bear", "exp": 23, "hp": 80},
    {"name": "Behemoth", "exp": 2500, "hp": 4000},
    {"name": "Bellicose Orger", "exp": 500, "hp": 700},
    {"name": "Berrypest", "exp": 0, "hp": 500},
    {"name": "Berserker Chicken", "exp": 220, "hp": 465},
    {"name": "Betrayed Wraith", "exp": 3500, "hp": 4200},
    {"name": "Bibby Bloodbath", "exp": 1500, "hp": 1200},
    {"name": "Big Boss Trolliver", "exp": 105, "hp": 150},
    {"name": "Biting Book", "exp": 9350, "hp": 6500},
    {"name": "Biting Cold", "exp": None, "hp": None},
    {"name": "Black Cobra", "exp": None, "hp": None},
    {"name": "Black Knight", "exp": 1600, "hp": 1800},
    {"name": "Black Sheep", "exp": 0, "hp": 20},
    {"name": "Black Sphinx Acolyte", "exp": 7200, "hp": 8100},
    {"name": "Black Vixen", "exp": 3200, "hp": 3200},
    {"name": "Blazing Fire Elemental", "exp": 450, "hp": 650},
    {"name": "Blemished Spawn", "exp": 5300, "hp": 9000},
    {"name": "Blightwalker", "exp": 5850, "hp": 8900},
    {"name": "Blistering Fire Elemental", "exp": 1300, "hp": 1500},
    {"name": "Blood Beast", "exp": 1000, "hp": 1600},
    {"name": "Blood Crab", "exp": 160, "hp": 290},
    {"name": "Blood Hand", "exp": 750, "hp": 700},
    {"name": "Blood Priest", "exp": 900, "hp": 820},
    {"name": "Blood Tear", "exp": 0, "hp": 3500},
    {"name": "Bloodback", "exp": 4000, "hp": 5200},
    {"name": "Bloodpaw", "exp": 50, "hp": 100},
    {"name": "Bloom of Doom", "exp": None, "hp": 30000},
    {"name": "Blue Djinn", "exp": 215, "hp": 330},
    {"name": "Blue Soul Stealer", "exp": None, "hp": None},
    {"name": "Boar", "exp": 60, "hp": 198},
    {"name": "Bog Frog", "exp": 0, "hp": 25},
    {"name": "Bog Raider", "exp": 800, "hp": 1300},
    {"name": "Bolfrim", "exp": 35000,
     "hp": 100000},  # TODO: not working
    {"name": "Bone Capsule", "exp": None, "hp": None},
    {"name": "Bone Jaw", "exp": 0, "hp": 4500},
    {"name": "Bonebeast", "exp": 580, "hp": 515},
    {"name": "Bonelord", "exp": 170, "hp": 260},
    {"name": "Bonny Bunny", "exp": 0, "hp": 200},
    {"name": "Bony Sea Devil", "exp": 19470, "hp": 24000},
    {"name": "Boogey", "exp": 475, "hp": 930},
    {"name": "Boogy", "exp": 950, "hp": 1300},
    {"name": "Boreth", "exp": 1800, "hp": 1400},
    {"name": "Bound Astral Power", "exp": None, "hp": None},
    {"name": "Bovinus", "exp": 60, "hp": 150},
    {"name": "Brachiodemon", "exp": 14080, "hp": 25000},
    {"name": "Bragrumol", "exp": 18000, "hp": 38000},
    {"name": "Brain Head", "exp": None, "hp": None},
    {"name": "Brain Squid", "exp": 17672, "hp": 18000},
    {"name": "Braindeath", "exp": 985, "hp": 1225},
    {"name": "Branchy Crawler", "exp": 19000, "hp": 27000},
    {"name": "Breach Brood", "exp": 1760, "hp": 3500},
    {"name": "Bretzecutioner", "exp": 3700, "hp": 5600},
    {"name": "Bride of Night", "exp": 450, "hp": 275},
    {"name": "Brimstone Bug", "exp": 900, "hp": 1300},
    {"name": "Brittle Skeleton", "exp": 35, "hp": 50},
    {"name": "Broken Shaper", "exp": 1600, "hp": 2200},
    {"name": "Brokul", "exp": 23000, "hp": 50000},
    {"name": "Brother Chill", "exp": None, "hp": None},
    {"name": "Brother Freeze", "exp": None, "hp": None},
    {"name": "Brother Worm", "exp": None, "hp": None},
    {"name": "Bruise Payne", "exp": 1000, "hp": 1600},
    {"name": "Brutus Bloodbeard", "exp": 795, "hp": 1555},
    {"name": "Bug", "exp": 18, "hp": 29},
    {"name": "Bullwark", "exp": 22000, "hp": 72000},
    {"name": "Burning Book", "exp": 11934, "hp": 18000},
    {"name": "Burning Gladiator", "exp": 7350, "hp": 10000},
    {"name": "Burrowing Beetle", "exp": None, "hp": None},
    {"name": "Burster", "exp": 10000, "hp": None},
    {"name": "Burster Spectre", "exp": 6000, "hp": 6500},
    {"name": "Butterfly", "exp": 0, "hp": 2},
    {"name": "Cake Golem", "exp": 100, "hp": 444},
    {"name": "Calamary", "exp": 0, "hp": 75},
    {"name": "Canopic Jar", "exp": 0, "hp": 1000},
    {"name": "Capricious Phantom", "exp": 19360, "hp": 30000},
    {"name": "Captain Jones", "exp": 620, "hp": 555},
    {"name": "Captured Dwarf", "exp": None, "hp": None},
    {"name": "Carniphila", "exp": 150, "hp": 255},
    {"name": "Carnisylvan Sapling", "exp": 0, "hp": 750},
    {"name": "Carrion Worm", "exp": 70, "hp": 145},
    {"name": "Cart Packed with Gold", "exp": 0, "hp": 10000},
    {"name": "Cat", "exp": 0, "hp": 20},
    {"name": "Cave Chimera", "exp": 6800, "hp": 8000},
    {"name": "Cave Devourer", "exp": 2380, "hp": 4500},
    {"name": "Cave Parrot", "exp": 0, "hp": 30},
    {"name": "Cave Rat", "exp": 10, "hp": 30},
    {"name": "Cave Spider", "exp": 2000, "hp": 1800},
    {"name": "Celebrating Orger", "exp": None, "hp": None},
    {"name": "Centipede", "exp": 34, "hp": 70},
    {"name": "Cerebellum", "exp": None, "hp": None},
    {"name": "Chakoya Toolshaper", "exp": 40, "hp": 80},
    {"name": "Chakoya Tribewarden", "exp": 40, "hp": 68},
    {"name": "Chakoya Windcaller", "exp": 48, "hp": 84},
    {"name": "Channeling Earl Osam", "exp": 0, "hp": None},
    {"name": "Charged Anomaly", "exp": None, "hp": 18000},
    {"name": "Charged Disruption", "exp": None, "hp": None},
    {"name": "Charged Energy Elemental", "exp": 450, "hp": 500},
    {"name": "Charger", "exp": 85, "hp": 1600},
    {"name": "Charging Outburst", "exp": 50000, "hp": 12000},
    {"name": "Chasm Spawn", "exp": 2700, "hp": 4500},
    {"name": "Cheese Thief", "exp": 0, "hp": 1100},
    {"name": "Chicken", "exp": 0, "hp": 15},
    {"name": "Chikhaton", "exp": 20000, "hp": 20000},
    {"name": "Chizzoron the Distorter", "exp": 4000, "hp": 16000},
    {"name": "Choking Fear", "exp": 4700, "hp": 5800},
    {"name": "Chopper", "exp": 5400, "hp": 7200},
    {"name": "Clay Guardian", "exp": 400, "hp": 625},
    {"name": "Cliff Strider", "exp": 5700, "hp": 9400},
    {"name": "Cloak of Terror", "exp": 19700, "hp": 28000},
    {"name": "Clomp", "exp": 475, "hp": 900},
    {"name": "Cobra", "exp": 30, "hp": 65},
    {"name": "Cobra Assassin", "exp": 6980, "hp": 8200},
    {"name": "Cobra Scout", "exp": 7310, "hp": 8500},
    {"name": "Cobra Vizier", "exp": 7650, "hp": 8500},
    {"name": "Cocoon", "exp": None, "hp": None},
    {"name": "Coldheart", "exp": 3500, "hp": 7000},
    {"name": "Colerian the Barbarian", "exp": 90, "hp": 265},
    {"name": "Concentrated Death", "exp": None, "hp": None},
    {"name": "Condensed Sin", "exp": 0, "hp": None},
    {"name": "Containment Crystal", "exp": 0, "hp": None},
    {"name": "Containment Machine", "exp": 0, "hp": 6500},
    {"name": "Control Tower", "exp": 3000, "hp": 7500},
    {"name": "Coral Frog", "exp": 20, "hp": 60},
    {"name": "Corrupted Soul", "exp": 1300, "hp": 1100},
    {"name": "Corym Charlatan", "exp": 150, "hp": 250},
    {"name": "Corym Skirmisher", "exp": 260, "hp": 450},
    {"name": "Corym Vanguard", "exp": 490, "hp": 700},
    {"name": "Cosmic Energy Prism A", "exp": 840, "hp": 1000},
    {"name": "Cosmic Energy Prism B", "exp": 840, "hp": 1000},
    {"name": "Cosmic Energy Prism C", "exp": 840, "hp": 1000},
    {"name": "Cosmic Energy Prism D", "exp": 840, "hp": 1000},
    {"name": "Count Vlarkorth", "exp": None, "hp": None},
    {"name": "Countess Sorrow", "exp": 13000, "hp": 6500},
    {"name": "Courage Leech", "exp": 18900, "hp": 27000},
    {"name": "Cow", "exp": 400, "hp": 700},
    {"name": "Crab", "exp": 30, "hp": 55},
    {"name": "Crackler", "exp": None, "hp": None},
    {"name": "Crawler", "exp": 1000, "hp": 1450},
    {"name": "Crazed Beggar", "exp": 35, "hp": 100},
    {"name": "Crazed Dwarf", "exp": 50, "hp": 105},
    {"name": "Crazed Summer Rearguard", "exp": 4700, "hp": 5300},
    {"name": "Crazed Summer Vanguard", "exp": 5000, "hp": 5500},
    {"name": "Crazed Winter Rearguard", "exp": 4700, "hp": 5200},
    {"name": "Crazed Winter Vanguard", "exp": 5400, "hp": 5800},
    {"name": "Crimson Frog", "exp": 20, "hp": 60},
    {"name": "Crocodile", "exp": 40, "hp": 105},
    {"name": "Crustacea Gigantica", "exp": 1800, "hp": 1600},
    {"name": "Crypt Defiler", "exp": 70, "hp": 185},
    {"name": "Crypt Shambler", "exp": 195, "hp": 330},
    {"name": "Crypt Warden", "exp": 8400, "hp": 8300},
    {"name": "Crypt Warrior", "exp": 4200, "hp": 7800},
    {"name": "Crystal Spider", "exp": 900, "hp": 1250},
    {"name": "Crystal Wolf", "exp": 275, "hp": 750},
    {"name": "Crystalcrusher", "exp": 500, "hp": 570},
    {"name": "Cublarc the Plunderer", "exp": 400, "hp": 400},
    {"name": "Cult Believer", "exp": 850, "hp": 975},
    {"name": "Cult Enforcer", "exp": 1000, "hp": 1150},
    {"name": "Cult Scholar", "exp": 1100, "hp": 1650},
    {"name": "Cursed Book", "exp": 13345, "hp": 20000},
    {"name": "Cursed Gladiator", "exp": 215, "hp": 435},
    {"name": "Cursed Prospector", "exp": 5250, "hp": 3900},
    {"name": "Custodian", "exp": 27500, "hp": 47000},
    {"name": "Cyclops", "exp": 150, "hp": 260},
    {"name": "Cyclops Drone", "exp": 200, "hp": 325},
    {"name": "Cyclops Smith", "exp": 255, "hp": 435},
    {"name": "Damage Resonance", "exp": None, "hp": 11000},
    {"name": "Damaged Crystal Golem", "exp": 0, "hp": 500},
    {"name": "Damaged Worker Golem", "exp": 95, "hp": 260},
    {"name": "Damned Soul", "exp": None, "hp": None},
    {"name": "Darakan the Executioner", "exp": 1600, "hp": 3480},
    {"name": "Dark Apprentice", "exp": 100, "hp": 225},
    {"name": "Dark Carnisylvan", "exp": 3900, "hp": 7500},
    {"name": "Dark Druid", "exp": None, "hp": None},
    {"name": "Dark Faun", "exp": 900, "hp": 1100},
    {"name": "Dark Knight", "exp": None, "hp": None},
    {"name": "Dark Knowledge", "exp": 0, "hp": None},
    {"name": "Dark Magician", "exp": 185, "hp": 325},
    {"name": "Dark Monk", "exp": 145, "hp": 190},
    {"name": "Dark Paladin", "exp": None, "hp": None},
    {"name": "Dark Sorcerer", "exp": None, "hp": None},
    {"name": "Dark Soul", "exp": None, "hp": None},
    {"name": "Dark Torturer", "exp": 4650, "hp": 7350},
    {"name": "Darkfang", "exp": 4000, "hp": 4800},
    {"name": "Dawn Bat", "exp": 10, "hp": 30},
    {"name": "Dawn Scorpion", "exp": 45, "hp": 65},
    {"name": "Dawnfire Asura", "exp": 4100, "hp": 2900},
    {"name": "Dawnfly", "exp": 35, "hp": 90},
    {"name": "Dazed Leaf Golem", "exp": 8000, "hp": 10000},
    {"name": "Deadeye Devious", "exp": 750, "hp": 1450},
    {"name": "Death Blob", "exp": 300, "hp": 320},
    {"name": "Death Dragon", "exp": None, "hp": 8350},
    {"name": "Death Priest", "exp": 750, "hp": 800},
    {"name": "Death Priest Shargon", "exp": None, "hp": 65000},
    {"name": "Death Reaper", "exp": None, "hp": None},
    {"name": "Deathbine", "exp": 340, "hp": 525},
    {"name": "Deathbringer", "exp": 5100, "hp": 8440},
    {"name": "Deathling Scout", "exp": 6300, "hp": 7200},
    {"name": "Deathling Spellsinger", "exp": 6400, "hp": 7200},
    {"name": "Deathslicer", "exp": 0, "hp": 8200},
    {"name": "Deathspawn", "exp": 0, "hp": 225},
    {"name": "Deathstrike", "exp": 40000, "hp": 200000},
    {"name": "Deep Terror", "exp": 35000, "hp": 100000},
    {"name": "Deepling Brawler", "exp": 260, "hp": 380},
    {"name": "Deepling Elite", "exp": 3000, "hp": 3200},
    {"name": "Deepling Guard", "exp": 2100, "hp": 1900},
    {"name": "Deepling Master Librarian", "exp": 1900, "hp": 1700},
    {"name": "Deepling Scout", "exp": 160, "hp": 240},
    {"name": "Deepling Spellsinger", "exp": 1000, "hp": 850},
    {"name": "Deepling Tyrant", "exp": 4200, "hp": 4500},
    {"name": "Deepling Warrior", "exp": 1500, "hp": 1600},
    {"name": "Deepling Worker", "exp": 130, "hp": 190},
    {"name": "Deepsea Blood Crab", "exp": 180, "hp": 320},
    {"name": "Deepworm", "exp": 2300, "hp": 3500},
    {"name": "Deer", "exp": 0, "hp": 25},
    {"name": "Defiler", "exp": 3700, "hp": 3650},
    {"name": "Delany", "exp": 30000,
     "hp": 100000},  # TODO: not working
    {"name": "Demodras", "exp": 6000, "hp": 4500},
    {"name": "Demon", "exp": 6000, "hp": 8200},
    {"name": "Demon Blood", "exp": 0, "hp": None},
    {"name": "Demon Outcast", "exp": 6200, "hp": 6900},
    {"name": "Demon Parrot", "exp": 225, "hp": 360},
    {"name": "Demon Skeleton", "exp": 240, "hp": 400},
    {"name": "Demon Slave", "exp": None, "hp": None},
    {"name": "Depolarized Crackler", "exp": None, "hp": None},
    {"name": "Depowered Minotaur", "exp": 1100, "hp": 1500},
    {"name": "Despair", "exp": None, "hp": 10000},
    {"name": "Desperate Soul", "exp": None, "hp": None},
    {"name": "Desperate White Deer", "exp": 35, "hp": 55},
    {"name": "Destabilized Ferumbras", "exp": None, "hp": None},
    {"name": "Destroyed Pillar", "exp": 0, "hp": 0},
    {"name": "Destroyer", "exp": 2500, "hp": 3700},
    {"name": "Devourer", "exp": 1755, "hp": 1900},
    {"name": "Devovorga", "exp": None, "hp": 500000},
    {"name": "Dharalion", "exp": 570, "hp": 380},
    {"name": "Diabolic Imp", "exp": 2900, "hp": 1950},
    {"name": "Diamond Servant", "exp": 700, "hp": 1000},
    {"name": "Diamond Servant Replica", "exp": 700, "hp": 2000},
    {"name": "Diblis the Fair", "exp": 1800, "hp": 1500},
    {"name": "Dipthrah", "exp": 2900, "hp": 4200},
    {"name": "Dire Penguin", "exp": 119, "hp": 173},
    {"name": "Diremaw", "exp": 2500, "hp": 3600},
    {"name": "Dirtbeard", "exp": 375, "hp": 630},
    {"name": "Diseased Bill", "exp": 300, "hp": 1000},
    {"name": "Diseased Dan", "exp": 300, "hp": 800},
    {"name": "Diseased Fred", "exp": 300, "hp": 1100},
    {"name": "Disgusting Ooze", "exp": None, "hp": None},
    {"name": "Disruption", "exp": None, "hp": 12000},
    {"name": "Distorted Phantom", "exp": 18870, "hp": 26000},
    {"name": "Doctor Perhaps", "exp": 325, "hp": 475},
    {"name": "Dog", "exp": 0, "hp": 20},
    {"name": "Domestikion", "exp": 0, "hp": 0},
    {"name": "Doom Deer", "exp": 200, "hp": 405},
    {"name": "Doomhowl", "exp": 3750, "hp": 8500},
    {"name": "Doomsday Cultist", "exp": 100, "hp": 125},
    {"name": "Dracola", "exp": 11000, "hp": 16200},
    {"name": "Dragon", "exp": 700, "hp": 1000},
    {"name": "Dragon Egg", "exp": None, "hp": None},
    {"name": "Dragon Essence", "exp": None, "hp": None},
    {"name": "Dragon Hatchling", "exp": 185, "hp": 380},
    {"name": "Dragon Lord", "exp": 2100, "hp": 1900},
    {"name": "Dragon Lord Hatchling", "exp": 645, "hp": 750},
    {"name": "Dragon Servant", "exp": None, "hp": None},
    {"name": "Dragon Warden", "exp": None, "hp": None},
    {"name": "Dragon Wrath", "exp": None, "hp": None},
    {"name": "Dragonking Zyrtarch", "exp": None, "hp": None},
    {"name": "Dragonling", "exp": 2200, "hp": 2600},
    {"name": "Draken Abomination", "exp": 3800, "hp": 6250},
    {"name": "Draken Elite", "exp": 4200, "hp": 5550},
    {"name": "Draken Spellweaver", "exp": 3100, "hp": 5000},
    {"name": "Draken Warmaster", "exp": 2400, "hp": 4150},
    {"name": "Draptor", "exp": 2400, "hp": 3000},
    {"name": "Drasilla", "exp": 700, "hp": 1260},
    {"name": "Dread Intruder", "exp": 2400, "hp": 4500},
    {"name": "Dread Minion", "exp": 0, "hp": None},
    {"name": "Dreadbeast", "exp": 250, "hp": 800},
    {"name": "Dreadful Disruptor", "exp": 14000, "hp": None},
    {"name": "Dreadful Harvester", "exp": None, "hp": None},
    {"name": "Dreadmaw", "exp": None, "hp": None},
    {"name": "Dreadwing", "exp": 3750, "hp": 8500},
    {"name": "Drillworm", "exp": 858, "hp": 1500},
    {"name": "Dromedary", "exp": 0, "hp": 45},
    {"name": "Druid Familiar", "exp": None, "hp": 20000},
    {"name": "Druid's Apparition", "exp": 18870, "hp": 25000},
    {"name": "Drume", "exp": 25000, "hp": 35000},
    {"name": "Dryad", "exp": 190, "hp": 310},
    {"name": "Duke Krule", "exp": 55000, "hp": None},
    {"name": "Duskbringer", "exp": 2600, "hp": 3550},
    {"name": "Dwarf", "exp": 45, "hp": 90},
    {"name": "Dwarf Dispenser", "exp": None, "hp": None},
    {"name": "Dwarf Geomancer", "exp": 265, "hp": 380},
    {"name": "Dwarf Guard", "exp": 165, "hp": 245},
    {"name": "Dwarf Henchman", "exp": 15, "hp": 350},
    {"name": "Dwarf Miner", "exp": 60, "hp": 120},
    {"name": "Dwarf Soldier", "exp": 70, "hp": 135},
    {"name": "Dworc Fleshhunter", "exp": 40, "hp": 85},
    {"name": "Dworc Venomsniper", "exp": 35, "hp": 80},
    {"name": "Dworc Voodoomaster", "exp": 55, "hp": 80},
    {"name": "Earl Osam", "exp": 55000, "hp": None},
    {"name": "Earth Elemental", "exp": 450, "hp": 650},
    {"name": "Earth Overlord", "exp": 2800, "hp": 4000},
    {"name": "Earworm", "exp": 2000, "hp": 4000},
    {"name": "Eating Dog", "exp": None, "hp": None},
    {"name": "Eclipse Knight", "exp": 4650, "hp": 45000},
    {"name": "Efreet", "exp": 410, "hp": 550},
    {"name": "Egg", "exp": 0, "hp": 800},  # TODO: not working
    {"name": "Ekatrix", "exp": 200, "hp": 500},
    {"name": "Elder Bonelord", "exp": 280, "hp": 500},
    {"name": "Elder Forest Fury", "exp": 330, "hp": 670},
    {"name": "Elder Mummy", "exp": 560, "hp": 850},
    {"name": "Elder Wyrm", "exp": 2500, "hp": 2700},
    {"name": "Elephant", "exp": 160, "hp": 320},
    {"name": "Elf", "exp": 42, "hp": 100},
    {"name": "Elf Arcanist", "exp": 175, "hp": 220},
    {"name": "Elf Overseer", "exp": 290, "hp": 500},
    {"name": "Elf Scout", "exp": 75, "hp": 160},
    {"name": "Elvira Hammerthrust", "exp": 165, "hp": 245},
    {"name": "Ember Beast", "exp": None, "hp": None},
    {"name": "Emerald Damselfly", "exp": 35, "hp": 90},
    {"name": "Empowered Glooth Horror", "exp": None, "hp": 25000},
    {"name": "Empty", "exp": None, "hp": None},
    {"name": "Energetic Book", "exp": 12034, "hp": 18500},
    {"name": "Energized Raging Mage", "exp": 0, "hp": 3500},
    {"name": "Energuardian of Tales", "exp": 11361, "hp": 14000},
    {"name": "Energy Elemental", "exp": 550, "hp": 500},
    {"name": "Energy Overlord", "exp": 2800, "hp": 4000},
    {"name": "Energy Pulse", "exp": None, "hp": None},
    {"name": "Enfeebled Silencer", "exp": 1100, "hp": 1100},
    {"name": "Enlightened of the Cult", "exp": 500, "hp": 700},
    {"name": "Enraged Bookworm", "exp": 55, "hp": 145},
    {"name": "Enraged Crystal Golem", "exp": 550, "hp": 700},
    {"name": "Enraged Sand Brood", "exp": None, "hp": None},
    {"name": "Enraged Soul", "exp": 120, "hp": 150},
    {"name": "Enraged Squirrel", "exp": 15, "hp": 35},
    {"name": "Enraged White Deer", "exp": 165, "hp": 255},
    {"name": "Enslaved Dwarf", "exp": 2700, "hp": 3800},
    {"name": "Enthralled Demon", "exp": None, "hp": 8200},
    {"name": "Enusat the Onyx Wing", "exp": 21500, "hp": 25000},
    {"name": "Eradicator", "exp": 50000, "hp": 290000},
    {"name": "Eruption of Destruction", "exp": 0, "hp": 8500},
    {"name": "Esmeralda", "exp": 600, "hp": 800},
    {"name": "Essence of Darkness", "exp": 30, "hp": None},
    {"name": "Essence of Malice", "exp": 150000, "hp": 250000},
    {"name": "Eternal Guardian", "exp": 1800, "hp": 2500},
    {"name": "Ethershreck", "exp": 5600, "hp": 9500},
    {"name": "Evil Mastermind", "exp": 675, "hp": 1295},
    {"name": "Evil Prospector", "exp": 9000, "hp": 8500},
    {"name": "Evil Sheep", "exp": 240, "hp": 350},
    {"name": "Evil Sheep Lord", "exp": 340, "hp": 400},
    {"name": "Execowtioner", "exp": 2400, "hp": 3500},
    {"name": "Exotic Bat", "exp": 1200, "hp": 1500},
    {"name": "Exotic Cave Spider", "exp": 1400, "hp": 1900},
    {"name": "Eye of the Seven", "exp": None, "hp": None},
    {"name": "Eyeless Devourer", "exp": 6000, "hp": 10000},
    {"name": "Faceless Bane", "exp": 14000, "hp": 17000},
    {"name": "Fahim the Wise", "exp": 1500, "hp": 2000},
    {"name": "Falcon Knight", "exp": 5985, "hp": 9000},
    {"name": "Falcon Paladin", "exp": 6544, "hp": 8500},
    {"name": "Fallen Challenger", "exp": 0, "hp": 9000},
    {"name": "Fallen Mooh'Tah Master Ghar", "exp": 4400, "hp": 7990},
    {"name": "Fat Porker", "exp": None, "hp": None},
    {"name": "Fatality", "exp": 3250, "hp": 6000},
    {"name": "Faun", "exp": 800, "hp": 900},
    {"name": "Fazzrah", "exp": 2600, "hp": 2955},
    {"name": "Fear", "exp": None, "hp": None},
    {"name": "Feeble Glooth Horror", "exp": None, "hp": 5000},
    {"name": "Feral Sphinx", "exp": 8800, "hp": 9800},
    {"name": "Fernfang", "exp": 600, "hp": 400},
    {"name": "Feroxa", "exp": None, "hp": None},
    {"name": "Ferumbras", "exp": 35000, "hp": 90000},
    {"name": "Ferumbras Essence", "exp": None, "hp": None},
    {"name": "Ferumbras Mortal Shell", "exp": 100000, "hp": 300000},
    {"name": "Ferumbras Soul Splinter", "exp": None, "hp": 90000},
    {"name": "Fetter", "exp": 0, "hp": 5500},
    {"name": "Feverish Citizen", "exp": 30, "hp": 125},
    {"name": "Feversleep", "exp": 4400, "hp": 5900},
    {"name": "Fiery Blood", "exp": 0, "hp": 25000},
    {"name": "Fiery Heart", "exp": None, "hp": None},
    {"name": "Filth Toad", "exp": 90, "hp": 185},
    {"name": "Fire Devil", "exp": 145, "hp": 200},
    {"name": "Fire Elemental", "exp": 220, "hp": 280},
    {"name": "Fire Overlord", "exp": 2800, "hp": 4000},
    {"name": "Firestarter", "exp": 80, "hp": 180},
    {"name": "Fish", "exp": 0, "hp": 25},
    {"name": "Flame of Omrafir", "exp": None, "hp": 800},
    {"name": "Flameborn", "exp": 2550, "hp": 3500},
    {"name": "Flamecaller Zazrak", "exp": 3031, "hp": 2690},
    {"name": "Flamethrower", "exp": None, "hp": None},
    {"name": "Flamingo", "exp": 0, "hp": 25},
    {"name": "Fleabringer", "exp": 100, "hp": 265},
    {"name": "Fleshcrawler", "exp": 1000, "hp": 1450},
    {"name": "Fleshslicer", "exp": 5500, "hp": 5700},
    {"name": "Flimsy Lost Soul", "exp": 4500, "hp": 4000},
    {"name": "Floating Savant", "exp": 8000, "hp": 8000},
    {"name": "Floor Blob", "exp": None, "hp": None},
    {"name": "Flying Book", "exp": 200, "hp": 500},
    {"name": "Food Wagon", "exp": None, "hp": None},
    {"name": "Force Field", "exp": 0, "hp": None},
    {"name": "Foreman Kneebiter", "exp": 445, "hp": 570},
    {"name": "Foreshock", "exp": None, "hp": None},
    {"name": "Forest Fury", "exp": 235, "hp": 480},
    {"name": "Fox", "exp": 15, "hp": 22},
    {"name": "Frazzlemaw", "exp": 3740, "hp": 4100},
    {"name": "Freakish Lost Soul", "exp": 7020, "hp": 7000},
    {"name": "Freed Soul", "exp": None, "hp": None},
    {"name": "Frenzy", "exp": None, "hp": 8210},
    {"name": "Frost Dragon", "exp": 2100, "hp": 1800},
    {"name": "Frost Dragon Hatchling", "exp": 745, "hp": 800},
    {"name": "Frost Flower Asura", "exp": 4200, "hp": 3500},
    {"name": "Frost Giant", "exp": 150, "hp": 270},
    {"name": "Frost Giantess", "exp": 150, "hp": 275},
    {"name": "Frost Servant", "exp": 0, "hp": 385},
    {"name": "Frost Spider", "exp": 0, "hp": 1250},
    {"name": "Frost Troll", "exp": 23, "hp": 55},
    {"name": "Frostfur", "exp": 35, "hp": 65},
    {"name": "Frozen Man", "exp": None, "hp": None},
    {"name": "Frozen Minion", "exp": None, "hp": None},
    {"name": "Frozen Soul", "exp": 0, "hp": None},
    {"name": "Fugue", "exp": 23000, "hp": 32000},
    {"name": "Furious Fire Elemental", "exp": 330, "hp": 280},
    {"name": "Furious Orc Berserker", "exp": 0, "hp": None},
    {"name": "Furious Scorpion", "exp": 12000, "hp": 15000},
    {"name": "Furious Troll", "exp": 185, "hp": 245},
    {"name": "Fury", "exp": 3600, "hp": 4100},
    {"name": "Fury of the Emperor", "exp": None, "hp": 51000},
    {"name": "Furyosa", "exp": 11500, "hp": 25000},
    {"name": "Gaffir", "exp": 25000, "hp": 48500},
    {"name": "Gang Member", "exp": 70, "hp": 295},
    {"name": "Gargoyle", "exp": 150, "hp": 250},
    {"name": "Gaz'haragoth", "exp": 1000000, "hp": 350000},
    {"name": "Gazer", "exp": 90, "hp": 120},
    {"name": "Gazer Spectre", "exp": 4200, "hp": 4500},
    {"name": "Gelidrazah the Frozen", "exp": 9000, "hp": 10000},
    {"name": "General Murius", "exp": 450, "hp": 550},
    {"name": "Ghastly Dragon", "exp": 4600, "hp": 7800},
    {"name": "Ghazbaran", "exp": 15000, "hp": 60000},
    {"name": "Ghost", "exp": 120, "hp": 150},
    {"name": "Ghost of a Planegazer", "exp": 1100, "hp": 1450},
    {"name": "Ghost Rat", "exp": 0, "hp": None},
    {"name": "Ghost Wolf", "exp": 65, "hp": 160},
    {"name": "Ghostly Apparition", "exp": 120, "hp": 150},
    {"name": "Ghoul", "exp": 85, "hp": 100},
    {"name": "Ghoulish Hyaena", "exp": 195, "hp": 400},
    {"name": "Ghulosh", "exp": 45000, "hp": None},
    {"name": "Ghulosh' Deathgaze", "exp": 0, "hp": None},
    {"name": "Giant Spider", "exp": 900, "hp": 1300},
    {"name": "Girtablilu Warrior", "exp": 5800, "hp": 8500},
    {"name": "Gladiator", "exp": 90, "hp": 185},
    {"name": "Glitterscale", "exp": 700, "hp": 1000},
    {"name": "Gloom Wolf", "exp": 70, "hp": 200},
    {"name": "Gloombringer", "exp": 6000, "hp": 50000},
    {"name": "Glooth Anemone", "exp": 1755, "hp": 2400},
    {"name": "Glooth Bandit", "exp": 2000, "hp": 2600},
    {"name": "Glooth Battery", "exp": 3000, "hp": 8000},
    {"name": "Glooth Blob", "exp": 700, "hp": 750},
    {"name": "Glooth Bomb", "exp": None, "hp": 250000},
    {"name": "Glooth Brigand", "exp": 1900, "hp": 2400},
    {"name": "Glooth Fairy", "exp": 19000, "hp": 59000},
    {"name": "Glooth Golem", "exp": 1606, "hp": 2700},
    {"name": "Glooth Horror", "exp": None, "hp": 15000},
    {"name": "Glooth Masher", "exp": None, "hp": None},
    {"name": "Glooth Powered Minotaur", "exp": None, "hp": None},
    {"name": "Glooth Slasher", "exp": None, "hp": None},
    {"name": "Glooth Trasher", "exp": None, "hp": None},
    {"name": "Glooth-Generator", "exp": 0, "hp": 12000},
    {"name": "Glowing Lava", "exp": 0, "hp": 0},
    {"name": "Gnarlhound", "exp": 60, "hp": 198},
    {"name": "Gnome Pack Crawler", "exp": None, "hp": None},
    {"name": "Gnomevil", "exp": 45000, "hp": 250000},
    {"name": "Gnorre Chyllson", "exp": 4000, "hp": 7150},
    {"name": "Goblin", "exp": 25, "hp": 50},
    {"name": "Goblin Assassin", "exp": 52, "hp": 75},
    {"name": "Goblin Leader", "exp": 75, "hp": 50},
    {"name": "Goblin Scavenger", "exp": 37, "hp": 60},
    {"name": "Golden Servant", "exp": 450, "hp": 550},
    {"name": "Golden Servant Replica", "exp": 450, "hp": 2000},
    {"name": "Goldhanded Cultist", "exp": 2000, "hp": 3000},
    {"name": "Goldhanded Cultist Bride", "exp": 2000, "hp": 3000},
    {"name": "Golgordan", "exp": 10000, "hp": 40000},
    {"name": "Gorgo", "exp": 7000, "hp": 4500},
    {"name": "Gorzindel", "exp": None, "hp": None},
    {"name": "Goshnar's Cruelty", "exp": None, "hp": None},
    {"name": "Goshnar's Greed", "exp": 150000, "hp": None},
    {"name": "Goshnar's Hatred", "exp": 75000, "hp": None},
    {"name": "Goshnar's Malice", "exp": None, "hp": None},
    {"name": "Goshnar's Megalomania", "exp": None, "hp": None},
    {"name": "Goshnar's Spite", "exp": None, "hp": None},
    {"name": "Gozzler", "exp": 180, "hp": 240},
    {"name": "Grand Canon Dominus", "exp": 11000, "hp": 15000},
    {"name": "Grand Chaplain Gaunder", "exp": None, "hp": None},
    {"name": "Grand Commander Soeren", "exp": None, "hp": None},
    {"name": "Grand Master Oberon", "exp": 20000, "hp": 30000},
    {"name": "Grand Mother Foulscale", "exp": 1400, "hp": 1850},
    {"name": "Grandfather Tridian", "exp": 1400, "hp": 1800},
    {"name": "Grave Guard", "exp": 485, "hp": 720},
    {"name": "Grave Robber", "exp": 65, "hp": 165},
    {"name": "Gravedigger", "exp": 950, "hp": 1500},
    {"name": "Gravelord Oshuran", "exp": 2400, "hp": 3100},
    {"name": "Greater Canopic Jar", "exp": 0, "hp": 7000},
    {"name": "Greater Death Minion", "exp": 0, "hp": 1500},
    {"name": "Greater Splinter of Madness", "exp": None, "hp": None},
    {"name": "Greed", "exp": None, "hp": None},
    {"name": "Greed Worm", "exp": None, "hp": None},
    {"name": "Greedbeast", "exp": 0, "hp": 0},
    {"name": "Green Djinn", "exp": 215, "hp": 330},
    {"name": "Green Frog", "exp": 0, "hp": 25},
    {"name": "Green Soul Stealer", "exp": None, "hp": None},
    {"name": "Grim Reaper", "exp": 5500, "hp": 3900},
    {"name": "Grimeleech", "exp": 7216, "hp": 9500},
    {"name": "Grimgor Guteater", "exp": 670, "hp": 1155},
    {"name": "Groam", "exp": 180, "hp": 400},
    {"name": "Grodrik", "exp": None, "hp": None},
    {"name": "Grorlam", "exp": 2400, "hp": 3000},
    {"name": "Grynch Clan Goblin", "exp": 4, "hp": 80},
    {"name": "Gryphon", "exp": 1000, "hp": 3200},
    {"name": "Guard Captain Quaid", "exp": 28000, "hp": 55000},
    {"name": "Guardian of Tales", "exp": 9204, "hp": 15000},
    {"name": "Guilt", "exp": None, "hp": None},
    {"name": "Gust of Wind", "exp": None, "hp": None},
    {"name": "Guzzlemaw", "exp": 6050, "hp": 6400},
    {"name": "Hairman the Huge", "exp": 335, "hp": 600},
    {"name": "Hand of Cursed Fate", "exp": 5000, "hp": 7500},
    {"name": "Harbinger of Darkness", "exp": 8700, "hp": 120000},
    {"name": "Hardened Usurper Archer", "exp": 0, "hp": 7300},
    {"name": "Hardened Usurper Knight", "exp": 0, "hp": 8200},
    {"name": "Hardened Usurper Warlock", "exp": 0, "hp": 7500},
    {"name": "Hatebreeder", "exp": 10000, "hp": 18000},
    {"name": "Hateful Soul", "exp": None, "hp": None},
    {"name": "Haunted Dragon", "exp": 6500, "hp": 6500},
    {"name": "Haunted Treeling", "exp": 310, "hp": 450},
    {"name": "Haunter", "exp": 4000, "hp": 8500},
    {"name": "Hazardous Phantom", "exp": 66000, "hp": None},
    {"name": "Hell Hole", "exp": None, "hp": None},
    {"name": "Hellfire Fighter", "exp": 3120, "hp": 3800},
    {"name": "Hellflayer", "exp": 11000, "hp": 14000},
    {"name": "Hellgorak", "exp": 10000, "hp": 25850},
    {"name": "Hellhound", "exp": 5440, "hp": 7500},
    {"name": "Hellspawn", "exp": 2550, "hp": 3500},
    {"name": "Hemming", "exp": 2850, "hp": 3000},
    {"name": "Heoni", "exp": 515, "hp": 900},
    {"name": "Herald of Gloom", "exp": 450, "hp": 340},
    {"name": "Hero", "exp": 1200, "hp": 1400},
    {"name": "Hibernal Moth", "exp": 700, "hp": 850},
    {"name": "Hide", "exp": 240, "hp": 500},
    {"name": "Hideous Fungus", "exp": 2900, "hp": 4600},
    {"name": "High Templar Cobrass", "exp": 515, "hp": 410},
    {"name": "High Voltage Elemental", "exp": 1500, "hp": 1500},
    {"name": "Hirintror", "exp": 800, "hp": 1500},
    {"name": "Hive Overseer", "exp": 5500, "hp": 7500},
    {"name": "Hive Pore", "exp": None, "hp": None},
    {"name": "Holy Bog Frog", "exp": 0, "hp": 25},
    {"name": "Honour Guard", "exp": 55, "hp": 85},
    {"name": "Hoodinion", "exp": 0, "hp": 0},
    {"name": "Horadron", "exp": 18000, "hp": 30000},
    {"name": "Horestis", "exp": 3500, "hp": 6000},
    {"name": "Horrible Dream", "exp": 0, "hp": None},
    {"name": "Horror", "exp": None, "hp": None},
    {"name": "Horse", "exp": 0, "hp": 75},
    {"name": "Hot Dog", "exp": 190, "hp": 505},
    {"name": "Hulking Carnisylvan", "exp": 4200, "hp": 8600},
    {"name": "Human", "exp": 50, "hp": 150},
    {"name": "Humongous Fungus", "exp": 2600, "hp": 3400},
    {"name": "Humorless Fungus", "exp": 0, "hp": 2500},
    {"name": "Hunger Worm", "exp": None, "hp": None},
    {"name": "Hunter", "exp": 150, "hp": 150},
    {"name": "Husky", "exp": 0, "hp": 140},
    {"name": "Hyaena", "exp": 20, "hp": 60},
    {"name": "Hydra", "exp": 2100, "hp": 2350},
    {"name": "Ice Dragon", "exp": 2300, "hp": 2500},
    {"name": "Ice Golem", "exp": 295, "hp": 385},
    {"name": "Ice Overlord", "exp": 2800, "hp": 4000},
    {"name": "Ice Witch", "exp": 580, "hp": 650},
    {"name": "Icecold Book", "exp": 12750, "hp": 21000},
    {"name": "Icicle", "exp": None, "hp": None},
    {"name": "Imp Intruder", "exp": None, "hp": None},
    {"name": "Incineron", "exp": 3500, "hp": 7000},
    {"name": "Incredibly Old Witch", "exp": None, "hp": None},
    {"name": "Infected Weeper", "exp": 1200, "hp": 3000},
    {"name": "Infernal Demon", "exp": 15560, "hp": 32000},
    {"name": "Infernal Frog", "exp": 190, "hp": 655},
    {"name": "Infernal Phantom", "exp": 14080, "hp": 26000},
    {"name": "Infernalist", "exp": 4000, "hp": 3650},
    {"name": "Ink Blob", "exp": 14450, "hp": 9500},
    {"name": "Inky", "exp": 250, "hp": 750},
    {"name": "Innocent Soul", "exp": None, "hp": None},
    {"name": "Insane Siren", "exp": 6000, "hp": 6500},
    {"name": "Insect Swarm", "exp": 40, "hp": 50},
    {"name": "Insectoid Scout", "exp": 150, "hp": 230},
    {"name": "Insectoid Worker", "exp": 650, "hp": 950},
    {"name": "Instable Breach Brood", "exp": 1100, "hp": 2200},
    {"name": "Instable Fire", "exp": 0, "hp": 1000},
    {"name": "Instable Sparkion", "exp": 1350, "hp": 1900},
    {"name": "Invading Demon", "exp": None, "hp": None},
    {"name": "Irahsae", "exp": 15000, "hp": 35000},
    {"name": "Irgix the Flimsy", "exp": 18000, "hp": 24000},
    {"name": "Iron Servant", "exp": 210, "hp": 350},
    {"name": "Iron Servant Replica", "exp": 210, "hp": 1000},
    {"name": "Ironblight", "exp": 4400, "hp": 6600},
    {"name": "Island Troll", "exp": 20, "hp": 50},
    {"name": "Izcandar Champion of Summer", "exp": None, "hp": None},
    {"name": "Izcandar Champion of Winter", "exp": 55000, "hp": None},
    {"name": "Izcandar the Banished", "exp": None, "hp": None},
    {"name": "Jagged Earth Elemental", "exp": 1300, "hp": 1500},
    {"name": "Jailer", "exp": 45, "hp": 65},
    {"name": "Jaul", "exp": 30000, "hp": 90000},
    {"name": "Jellyfish", "exp": 0, "hp": 55},
    {"name": "Jesse the Wicked", "exp": 180, "hp": 280},
    {"name": "Juggernaut", "exp": 11200, "hp": 20000},
    {"name": "Juvenile Bashmu", "exp": 4500, "hp": 7500},
    {"name": "Juvenile Cyclops", "exp": 130, "hp": 260},
    {"name": "Kalyassa", "exp": 9000, "hp": 10000},
    {"name": "Katex Blood Tongue", "exp": 5000, "hp": 6300},
    {"name": "Kerberos", "exp": 10000, "hp": 11000},
    {"name": "Kesar", "exp": None, "hp": None},
    {"name": "Killer Caiman", "exp": 900, "hp": 1500},
    {"name": "Killer Rabbit", "exp": 160, "hp": 205},
    {"name": "King Chuck", "exp": None, "hp": None},
    {"name": "King Zelos", "exp": None, "hp": None},
    {"name": "Kitty", "exp": None, "hp": None},
    {"name": "Knight Familiar", "exp": None, "hp": 10000},
    {"name": "Knight's Apparition", "exp": 18870, "hp": 25000},
    {"name": "Knowledge Elemental", "exp": 10603, "hp": 10500},
    {"name": "Knowledge Raider", "exp": 0, "hp": None},
    {"name": "Kollos", "exp": 2400, "hp": 3800},
    {"name": "Kongra", "exp": 115, "hp": 340},
    {"name": "Koshei the Deathless", "exp": 0, "hp": 3000},
    {"name": "Kraknaknork", "exp": 300, "hp": 80},
    {"name": "Kreebosh the Exile", "exp": 350, "hp": 705},
    {"name": "Kroazur", "exp": 2700, "hp": 3000},
    {"name": "Lacewing Moth", "exp": 800, "hp": 900},
    {"name": "Lady Tenebris", "exp": None, "hp": None},
    {"name": "Ladybug", "exp": 70, "hp": 255},
    {"name": "Lamassu", "exp": 9000, "hp": 8700},
    {"name": "Lancer Beetle", "exp": 275, "hp": 400},
    {"name": "Larva", "exp": 44, "hp": 70},
    {"name": "Last Planegazer", "exp": None, "hp": 50000},
    {"name": "Latrivan", "exp": 10000, "hp": 25000},
    {"name": "Lava Golem", "exp": 6200, "hp": 9000},
    {"name": "Lava Lurker", "exp": 4000, "hp": 5900},
    {"name": "Lava Lurker Attendant", "exp": None, "hp": None},
    {"name": "Lavafungus", "exp": 6200, "hp": 7200},
    {"name": "Lavahole", "exp": None, "hp": None},
    {"name": "Lavaworm", "exp": 6500, "hp": 7500},
    {"name": "Leaf Golem", "exp": 45, "hp": 90},
    {"name": "Leiden", "exp": None, "hp": None},
    {"name": "Lersatio", "exp": 2500, "hp": 1645},
    {"name": "Lesser Death Minion", "exp": 0, "hp": 550},
    {"name": "Lesser Fire Devil", "exp": 110, "hp": 175},
    {"name": "Lesser Splinter of Madness", "exp": None, "hp": None},
    {"name": "Lesser Swarmer", "exp": 0, "hp": 230},
    {"name": "Lethal Lissy", "exp": 500, "hp": 1450},
    {"name": "Leviathan", "exp": 5000, "hp": 6000},
    {"name": "Librarian", "exp": 0, "hp": 11000},
    {"name": "Lich", "exp": 900, "hp": 880},
    {"name": "Lion", "exp": 30, "hp": 80},
    {"name": "Lion Archer", "exp": 0, "hp": 7300},
    {"name": "Lion Commander", "exp": 0, "hp": 8500},
    {"name": "Lion Knight", "exp": 0, "hp": 8200},
    {"name": "Lion Warlock", "exp": 0, "hp": 7500},
    {"name": "Lionet", "exp": 35000, "hp": 100000},
    {"name": "Liquor Spirit", "exp": 0, "hp": None},
    {"name": "Lisa", "exp": 18000, "hp": 55000},
    {"name": "Little Corym Charlatan", "exp": 40, "hp": 90},
    {"name": "Lizard Abomination", "exp": None, "hp": 95000},
    {"name": "Lizard Chosen", "exp": 2200, "hp": 3050},
    {"name": "Lizard Dragon Priest", "exp": 1320, "hp": 1450},
    {"name": "Lizard Gate Guardian", "exp": 2500, "hp": 5000},
    {"name": "Lizard High Guard", "exp": 1450, "hp": 1800},
    {"name": "Lizard Legionnaire", "exp": 1100, "hp": 1400},
    {"name": "Lizard Magistratus", "exp": 2000, "hp": 6250},
    {"name": "Lizard Noble", "exp": 2000, "hp": 7000},
    {"name": "Lizard Sentinel", "exp": 110, "hp": 265},
    {"name": "Lizard Snakecharmer", "exp": 210, "hp": 325},
    {"name": "Lizard Templar", "exp": 155, "hp": 410},
    {"name": "Lizard Zaogun", "exp": 1700, "hp": 2955},
    {"name": "Lloyd", "exp": None, "hp": None},
    {"name": "Lokathmor", "exp": None, "hp": None},
    {"name": "Lonely Deer", "exp": None, "hp": None},
    {"name": "Lonely Frazzlemaw", "exp": None, "hp": None},
    {"name": "Lonely Polar Bear", "exp": None, "hp": None},
    {"name": "Lonely Rotworm", "exp": None, "hp": None},
    {"name": "Lonely Scorpion", "exp": None, "hp": None},
    {"name": "Lonely Snake", "exp": None, "hp": None},
    {"name": "Lonely Souleater", "exp": None, "hp": None},
    {"name": "Lonely Yielothax", "exp": None, "hp": None},
    {"name": "Lord Azaram", "exp": 55000, "hp": None},
    {"name": "Lord of the Elements", "exp": 8000, "hp": 8000},
    {"name": "Loricate Orger", "exp": 570, "hp": 750},
    {"name": "Lost Basher", "exp": 1800, "hp": 2600},
    {"name": "Lost Berserker", "exp": 4400, "hp": 5900},
    {"name": "Lost Exile", "exp": 1800, "hp": 1600},
    {"name": "Lost Ghost of a Planegazer", "exp": None, "hp": None},
    {"name": "Lost Gnome", "exp": 0, "hp": 10000},
    {"name": "Lost Husher", "exp": 1800, "hp": 1600},
    {"name": "Lost Soul", "exp": 4000, "hp": 5800},
    {"name": "Lost Thrower", "exp": 1200, "hp": 1700},
    {"name": "Lost Time", "exp": None, "hp": None},
    {"name": "Lucifuga Aranea", "exp": 10000, "hp": 12000},
    {"name": "Lumbering Carnivor", "exp": 1452, "hp": 2600},
    {"name": "Lyxoph", "exp": 10000, "hp": 45000},
    {"name": "Mad Mage", "exp": 1800, "hp": 2500},
    {"name": "Mad Scientist", "exp": 205, "hp": 325},
    {"name": "Mad Sheep", "exp": 0, "hp": 22},
    {"name": "Mad Technomancer", "exp": 55, "hp": 1800},
    {"name": "Madareth", "exp": 10000, "hp": 75000},
    {"name": "Magic Pillar", "exp": None, "hp": None},
    {"name": "Magical Sphere", "exp": 0, "hp": None},
    {"name": "Magicthrower", "exp": None, "hp": None},
    {"name": "Magma Crawler", "exp": 2700, "hp": 4800},
    {"name": "Magma Fiend", "exp": 0, "hp": 1600},
    {"name": "Magnor Mournbringer", "exp": 0, "hp": None},
    {"name": "Mahatheb", "exp": 600, "hp": 650},
    {"name": "Mahrdis", "exp": 3050, "hp": 3900},
    {"name": "Makeshift Home", "exp": None, "hp": None},
    {"name": "Malicious Minion", "exp": 0, "hp": 4000},
    {"name": "Malicious Soul", "exp": None, "hp": None},
    {"name": "Malofur Mangrinder", "exp": None, "hp": None},
    {"name": "Mamma Longlegs", "exp": 2200, "hp": 1800},
    {"name": "Mammoth", "exp": 160, "hp": 320},
    {"name": "Man in the Cave", "exp": 777, "hp": 485},
    {"name": "Manta Ray", "exp": 125, "hp": 680},
    {"name": "Manticore", "exp": 5100, "hp": 6700},
    {"name": "Many Faces", "exp": 18870, "hp": 30000},
    {"name": "Marid", "exp": 410, "hp": 550},
    {"name": "Marsh Stalker", "exp": 50, "hp": 100},
    {"name": "Marziel", "exp": 3000, "hp": 1900},
    {"name": "Massacre", "exp": 20000, "hp": 32000},
    {"name": "Massive Earth Elemental", "exp": 950, "hp": 1330},
    {"name": "Massive Energy Elemental", "exp": 950, "hp": 1100},
    {"name": "Massive Fire Elemental", "exp": 1400, "hp": 1800},
    {"name": "Massive Water Elemental", "exp": 1100, "hp": 1250},
    {"name": "Maw", "exp": 6500, "hp": 8200},
    {"name": "Mawhawk", "exp": 14000, "hp": 45000},
    {"name": "Maxxenius", "exp": 55000, "hp": None},
    {"name": "Mazoran", "exp": 50000, "hp": 290000},
    {"name": "Mazzinor", "exp": None, "hp": None},
    {"name": "Meadow Strider", "exp": 50, "hp": 100},
    {"name": "Mean Lost Soul", "exp": 5580, "hp": 5000},
    {"name": "Mean Maw", "exp": None, "hp": None},
    {"name": "Mean Minion", "exp": None, "hp": None},
    {"name": "Mean Termite", "exp": 0, "hp": 4300},
    {"name": "Mearidion", "exp": 0, "hp": 0},
    {"name": "Mechanical Fighter", "exp": 255, "hp": 420},
    {"name": "Medusa", "exp": 4050, "hp": 4500},
    {"name": "Megasylvan Yselda", "exp": None, "hp": None},
    {"name": "Melting Frozen Horror", "exp": None, "hp": None},
    {"name": "Menace", "exp": 3250, "hp": 6000},
    {"name": "Menacing Carnivor", "exp": 2112, "hp": 3500},
    {"name": "Mephiles", "exp": 415, "hp": 415},
    {"name": "Mercury Blob", "exp": 180, "hp": 150},
    {"name": "Merikh the Slaughterer", "exp": 1500, "hp": 2000},
    {"name": "Merlkin", "exp": 145, "hp": 235},
    {"name": "Metal Gargoyle", "exp": 1278, "hp": 2100},
    {"name": "Mezlon the Defiler", "exp": 50000, "hp": None},
    {"name": "Midnight Asura", "exp": 4100, "hp": 3100},
    {"name": "Midnight Panther", "exp": 900, "hp": 1200},
    {"name": "Midnight Spawn", "exp": 900, "hp": 2000},
    {"name": "Midnight Warrior", "exp": 750, "hp": 1000},
    {"name": "Mighty Splinter of Madness", "exp": None, "hp": None},
    {"name": "Mimic", "exp": 0, "hp": 30},
    {"name": "Mind-Wrecking Dream", "exp": 0, "hp": None},
    {"name": "Mindmasher", "exp": 6000, "hp": 9500},
    {"name": "Minion of Gaz'haragoth", "exp": 0, "hp": 5500},
    {"name": "Minion of Versperoth", "exp": 0, "hp": None},
    {"name": "Minotaur", "exp": 50, "hp": 100},
    {"name": "Minotaur Amazon", "exp": 2200, "hp": 2600},
    {"name": "Minotaur Archer", "exp": 65, "hp": 100},
    {"name": "Minotaur Bruiser", "exp": 50, "hp": 100},
    {"name": "Minotaur Cult Follower", "exp": 950, "hp": 1600},
    {"name": "Minotaur Cult Prophet", "exp": 1100, "hp": 1700},
    {"name": "Minotaur Cult Zealot", "exp": 1350, "hp": 1800},
    {"name": "Minotaur Guard", "exp": 160, "hp": 185},
    {"name": "Minotaur Hunter", "exp": 1700, "hp": 1400},
    {"name": "Minotaur Idol", "exp": None, "hp": None},
    {"name": "Minotaur Invader", "exp": 1600, "hp": 1850},
    {"name": "Minotaur Mage", "exp": 150, "hp": 155},
    {"name": "Minotaur Occultist", "exp": 100, "hp": 125},
    {"name": "Minotaur Poacher", "exp": 55, "hp": 160},
    {"name": "Minotaur Totem", "exp": 500, "hp": 6000},
    {"name": "Mirade", "exp": 30000, "hp": 100000},
    {"name": "Mirror Image", "exp": 27000, "hp": 35000},
    {"name": "Misguided Bully", "exp": 1200, "hp": 2000},
    {"name": "Misguided Shadow", "exp": 1500, "hp": 3000},
    {"name": "Misguided Thief", "exp": 1200, "hp": 1800},
    {"name": "Modified Gnarlhound", "exp": 0, "hp": 1500},
    {"name": "Mole", "exp": 100, "hp": 200},
    {"name": "Monk", "exp": 200, "hp": 240},
    {"name": "Monk of the Order", "exp": 200, "hp": 240},
    {"name": "Monstor", "exp": 575, "hp": 960},
    {"name": "Mooh'Tah Master", "exp": None, "hp": None},
    {"name": "Mooh'Tah Warrior", "exp": 900, "hp": 1200},
    {"name": "Moohtant", "exp": 2600, "hp": 3200},
    {"name": "Moohtant Wallbreaker", "exp": None, "hp": 250000},
    {"name": "Morgaroth", "exp": 15000, "hp": 55000},
    {"name": "Morguthis", "exp": 3000, "hp": 4800},
    {"name": "Morik the Gladiator", "exp": 160, "hp": 1235},
    {"name": "Mornenion", "exp": 115, "hp": 190},
    {"name": "Mould Phantom", "exp": 19500, "hp": 28000},
    {"name": "Mountain Troll", "exp": 12, "hp": 30},
    {"name": "Mounted Thorn Knight", "exp": 15000, "hp": None},
    {"name": "Mozradek", "exp": 21000, "hp": 28000},
    {"name": "Mr. Punish", "exp": 9000, "hp": 22000},
    {"name": "Muddy Earth Elemental", "exp": 450, "hp": 650},
    {"name": "Muglex Clan Assassin", "exp": 48, "hp": 75},
    {"name": "Muglex Clan Footman", "exp": 25, "hp": 50},
    {"name": "Muglex Clan Scavenger", "exp": 37, "hp": 60},
    {"name": "Mummy", "exp": 150, "hp": 240},
    {"name": "Munster", "exp": 35, "hp": 58},
    {"name": "Murderous Ghost", "exp": 0, "hp": 1500},
    {"name": "Murmillion", "exp": 0, "hp": 0},
    {"name": "Museum Stone Golem", "exp": 160, "hp": 270},
    {"name": "Museum Stone Rhino", "exp": 1800, "hp": 3000},
    {"name": "Mushroom Sniffer", "exp": 0, "hp": 250},
    {"name": "Mutated Bat", "exp": 615, "hp": 900},
    {"name": "Mutated Human", "exp": 150, "hp": 240},
    {"name": "Mutated Rat", "exp": 450, "hp": 550},
    {"name": "Mutated Tiger", "exp": 750, "hp": 1100},
    {"name": "Mutated Zalamon", "exp": None, "hp": 155000},
    {"name": "Mystic Energy", "exp": None, "hp": None},
    {"name": "Nargol the Impaler", "exp": 0, "hp": None},
    {"name": "Necromancer", "exp": 580, "hp": 580},
    {"name": "Necromancer Servant", "exp": 590, "hp": 600},
    {"name": "Necromantic Energy", "exp": None, "hp": None},
    {"name": "Necropharus", "exp": 1050, "hp": 750},
    {"name": "Neferi the Spy", "exp": 19650, "hp": 28000},
    {"name": "Neutral Deepling Warrior", "exp": 1500, "hp": 1600},
    {"name": "Nightfiend", "exp": 2100, "hp": 2700},
    {"name": "Nightmare", "exp": 1666, "hp": 2700},
    {"name": "Nightmare of Gaz'haragoth", "exp": 0, "hp": 5500},
    {"name": "Nightmare Scion", "exp": 1350, "hp": 1400},
    {"name": "Nightmare Tendril", "exp": 0, "hp": None},
    {"name": "Nightmarish Dream", "exp": 0, "hp": None},
    {"name": "Nightslayer", "exp": 250, "hp": 400},
    {"name": "Nightstalker", "exp": 500, "hp": 700},
    {"name": "Noble Lion", "exp": 400, "hp": 1000},
    {"name": "Nomad", "exp": 60, "hp": 160},
    {"name": "Norgle Glacierbeard", "exp": 2100, "hp": 4280},
    {"name": "Northern Pike", "exp": 0, "hp": 95},
    {"name": "Novice of the Cult", "exp": 100, "hp": 285},
    {"name": "Nymph", "exp": 850, "hp": 900},
    {"name": "Obujos", "exp": 20000, "hp": 35000},
    {"name": "Ocyakao", "exp": 490, "hp": 700},
    {"name": "Ogre Brute", "exp": 800, "hp": 1000},
    {"name": "Ogre Rowdy", "exp": 4200, "hp": 4500},
    {"name": "Ogre Ruffian", "exp": 5000, "hp": 5500},
    {"name": "Ogre Sage", "exp": 5500, "hp": 4800},
    {"name": "Ogre Savage", "exp": 950, "hp": 1400},
    {"name": "Ogre Shaman", "exp": 625, "hp": 800},
    {"name": "Omnivora", "exp": 750, "hp": 1200},
    {"name": "Omrafir", "exp": None, "hp": 322000},
    {"name": "Omruc", "exp": 2950, "hp": 4300},
    {"name": "Oodok Witchmaster", "exp": 550, "hp": 450},
    {"name": "Orc", "exp": 25, "hp": 70},
    {"name": "Orc Berserker", "exp": 195, "hp": 210},
    {"name": "Orc Cult Fanatic", "exp": 1100, "hp": 1300},
    {"name": "Orc Cult Inquisitor", "exp": 1150, "hp": 1500},
    {"name": "Orc Cult Minion", "exp": 850, "hp": 1000},
    {"name": "Orc Cult Priest", "exp": 1000, "hp": 1300},
    {"name": "Orc Cultist", "exp": 950, "hp": 1350},
    {"name": "Orc Leader", "exp": 270, "hp": 450},
    {"name": "Orc Marauder", "exp": 205, "hp": 235},
    {"name": "Orc Musician", "exp": None, "hp": None},
    {"name": "Orc Rider", "exp": 110, "hp": 180},
    {"name": "Orc Shaman", "exp": 110, "hp": 115},
    {"name": "Orc Spearman", "exp": 38, "hp": 105},
    {"name": "Orc Warlord", "exp": 670, "hp": 950},
    {"name": "Orc Warrior", "exp": 50, "hp": 125},
    {"name": "Orchid Frog", "exp": 20, "hp": 60},
    {"name": "Orclops Doomhauler", "exp": 1200, "hp": 1700},
    {"name": "Orclops Ravager", "exp": 1100, "hp": 1200},
    {"name": "Orcus the Cruel", "exp": 280, "hp": 480},
    {"name": "Orewalker", "exp": 4800, "hp": 7200},
    {"name": "Organic Matter", "exp": None, "hp": None},
    {"name": "Orger", "exp": 550, "hp": 700},
    {"name": "Orger Treasure", "exp": 0, "hp": 50000},
    {"name": "Orshabaal", "exp": 10000, "hp": 22500},
    {"name": "Outburst", "exp": 50000, "hp": 290000},
    {"name": "Overcharge", "exp": 0, "hp": 8000},
    {"name": "Overcharged Disruption", "exp": None, "hp": None},
    {"name": "Overcharged Energy Element", "exp": 1300, "hp": 1200},
    {"name": "Owin", "exp": 5000, "hp": 9600},
    {"name": "Paiz the Pauperizer", "exp": 6300, "hp": 8500},
    {"name": "Paladin Familiar", "exp": None, "hp": 15000},
    {"name": "Paladin's Apparition", "exp": 18870, "hp": 25000},
    {"name": "Panda", "exp": 23, "hp": 80},
    {"name": "Parasite", "exp": 0, "hp": 550},
    {"name": "Parrot", "exp": 0, "hp": 25},
    {"name": "Party Skeleton", "exp": 0, "hp": 40},
    {"name": "Penciljack", "exp": 35000, "hp": 150000},
    {"name": "Penguin", "exp": 1, "hp": 33},
    {"name": "Percht", "exp": 600, "hp": 620},
    {"name": "Percht Minion", "exp": None, "hp": None},
    {"name": "Phantasm", "exp": 4400, "hp": 3950},
    {"name": "Phantasm", "exp": 1, "hp": 65},
    {"name": "Phobia", "exp": None, "hp": None},
    {"name": "Phrodomo", "exp": 44000, "hp": 90000},
    {"name": "Pig", "exp": 0, "hp": 25},
    {"name": "Pigeon", "exp": 0, "hp": 30},
    {"name": "Pillar", "exp": None, "hp": None},
    {"name": "Pillar of Death", "exp": 0, "hp": None},
    {"name": "Pillar of Draining", "exp": 0, "hp": None},
    {"name": "Pillar of Healing", "exp": 0, "hp": None},
    {"name": "Pillar of Protection", "exp": 0, "hp": None},
    {"name": "Pillar of Summoning", "exp": 0, "hp": None},
    {"name": "Pirat Bombardier", "exp": 1700, "hp": 2300},
    {"name": "Pirat Cutthroat", "exp": 1800, "hp": 2600},
    {"name": "Pirat Guard", "exp": None, "hp": None},
    {"name": "Pirat Mate", "exp": 2400, "hp": 3200},
    {"name": "Pirat Patrol", "exp": None, "hp": None},
    {"name": "Pirat Scoundrel", "exp": 1600, "hp": 2200},
    {"name": "Pirate Buccaneer", "exp": 250, "hp": 425},
    {"name": "Pirate Corsair", "exp": 350, "hp": 675},
    {"name": "Pirate Cutthroat", "exp": 175, "hp": 325},
    {"name": "Pirate Ghost", "exp": 250, "hp": 275},
    {"name": "Pirate Marauder", "exp": 125, "hp": 210},
    {"name": "Pirate Skeleton", "exp": 85, "hp": 190},
    {"name": "Pit Battler", "exp": 0, "hp": 1150},
    {"name": "Pit Berserker", "exp": 0, "hp": 1800},
    {"name": "Pit Blackling", "exp": 0, "hp": 2350},
    {"name": "Pit Brawler", "exp": 0, "hp": 1600},
    {"name": "Pit Condemned", "exp": 0, "hp": 1500},
    {"name": "Pit Demon", "exp": 0, "hp": 1100},
    {"name": "Pit Destroyer", "exp": 0, "hp": 2000},
    {"name": "Pit Fiend", "exp": 0, "hp": 1050},
    {"name": "Pit Groveller", "exp": 0, "hp": 950},
    {"name": "Pit Grunt", "exp": 0, "hp": 1000},
    {"name": "Pit Lord", "exp": 0, "hp": 2400},
    {"name": "Pit Maimer", "exp": 0, "hp": 1200},
    {"name": "Pit Overlord", "exp": 0, "hp": 3000},
    {"name": "Pit Reaver", "exp": 0, "hp": 1350},
    {"name": "Pit Scourge", "exp": 0, "hp": 1400},
    {"name": "Pixie", "exp": 700, "hp": 770},
    {"name": "Piñata Dragon", "exp": 50, "hp": 10000},
    {"name": "Plagirath", "exp": 50000, "hp": 290000},
    {"name": "Plagueroot", "exp": 55000, "hp": None},
    {"name": "Plaguesmith", "exp": 3555, "hp": 8250},
    {"name": "Plaguethrower", "exp": None, "hp": None},
    {"name": "Planedweller", "exp": None, "hp": None},
    {"name": "Planestrider", "exp": None, "hp": None},
    {"name": "Plant Abomination", "exp": 0, "hp": 3900},
    {"name": "Plant Attendant", "exp": 0, "hp": None},
    {"name": "Poacher", "exp": 70, "hp": 90},
    {"name": "Poison Spider", "exp": 22, "hp": 26},
    {"name": "Poisonous Carnisylvan", "exp": 3900, "hp": 8000},
    {"name": "Polar Bear", "exp": 28, "hp": 85},
    {"name": "Poodle", "exp": 0, "hp": 20},
    {"name": "Pooka", "exp": 500, "hp": 500},
    {"name": "Poor Soul", "exp": None, "hp": None},
    {"name": "Possessed Tree", "exp": 1300, "hp": 2500},
    {"name": "Powerful Soul", "exp": None, "hp": None},
    {"name": "Preceptor Lazare", "exp": None, "hp": None},
    {"name": "Priestess", "exp": 420, "hp": 390},
    {"name": "Priestess of the Wild Sun", "exp": 6400, "hp": 8500},
    {"name": "Prince Drazzak", "exp": 210000, "hp": 330000},
    {"name": "Professor Maxxen", "exp": 15500, "hp": 90000},
    {"name": "Putrid Mummy", "exp": 900, "hp": 1500},
    {"name": "Pythius the Rotten", "exp": 7000, "hp": 9000},
    {"name": "Quara Constrictor", "exp": 250, "hp": 450},
    {"name": "Quara Constrictor Scout", "exp": 200, "hp": 450},
    {"name": "Quara Hydromancer", "exp": 800, "hp": 1100},
    {"name": "Quara Hydromancer Scout", "exp": 800, "hp": 1100},
    {"name": "Quara Mantassin", "exp": 400, "hp": 800},
    {"name": "Quara Mantassin Scout", "exp": 100, "hp": 220},
    {"name": "Quara Pincher", "exp": 1200, "hp": 1800},
    {"name": "Quara Pincher Scout", "exp": 600, "hp": 775},
    {"name": "Quara Predator", "exp": 1600, "hp": 2200},
    {"name": "Quara Predator Scout", "exp": 400, "hp": 890},
    {"name": "Quara Saboteur", "exp": 0, "hp": 7000},
    {"name": "Queen Nostalgia", "exp": 0, "hp": None},
    {"name": "Rabbit", "exp": 0, "hp": 15},
    {"name": "Raccoon Supplies", "exp": None, "hp": None},
    {"name": "Rage of Mazoran", "exp": 0, "hp": 4500},
    {"name": "Rage Squid", "exp": 14820, "hp": 17000},
    {"name": "Ragiaz", "exp": 50000, "hp": None},
    {"name": "Raging Fire", "exp": 1500, "hp": 1800},
    {"name": "Raging Mage", "exp": 3250, "hp": 3500},
    {"name": "Rahemos", "exp": 3100, "hp": 3700},
    {"name": "Rat", "exp": 5, "hp": 20},
    {"name": "Ratmiral Blackwhiskers", "exp": None, "hp": None},
    {"name": "Ravenous Beyondling", "exp": None, "hp": None},
    {"name": "Ravenous Hunger", "exp": None, "hp": None},
    {"name": "Ravenous Lava Lurker", "exp": 4000, "hp": 5000},
    {"name": "Raxias", "exp": 900, "hp": 1100},
    {"name": "Razzagorn", "exp": 50000, "hp": 290000},
    {"name": "Reality Reaver", "exp": 2480, "hp": 3900},
    {"name": "Realityquake", "exp": None, "hp": 110000},
    {"name": "Red Soul Stealer", "exp": None, "hp": None},
    {"name": "Redeemed Soul", "exp": 0, "hp": 250},
    {"name": "Reflection of a Mage", "exp": 3250, "hp": 3500},
    {"name": "Reflection of Mawhawk", "exp": 14000, "hp": 45000},
    {"name": "Reflection of Obujos", "exp": None, "hp": None},
    {"name": "Regenerating Mass", "exp": 0, "hp": None},
    {"name": "Rejana", "exp": 30000, "hp": 100000},
    {"name": "Renegade Knight", "exp": 1200, "hp": 1450},
    {"name": "Renegade Orc", "exp": 270, "hp": 450},
    {"name": "Renegade Quara Constrictor", "exp": 1250, "hp": 1500},
    {"name": "Renegade Quara Hydromancer", "exp": 1800, "hp": 2000},
    {"name": "Renegade Quara Mantassin", "exp": 1000, "hp": 1200},
    {"name": "Renegade Quara Pincher", "exp": 2200, "hp": 2800},
    {"name": "Renegade Quara Predator", "exp": 2700, "hp": 3250},
    {"name": "Retainer of Baeloc", "exp": 0, "hp": None},
    {"name": "Retching Horror", "exp": 4100, "hp": 5300},
    {"name": "Rewar the Bloody", "exp": None, "hp": None},
    {"name": "Ribstride", "exp": 1100, "hp": 1000},
    {"name": "Rift Breacher", "exp": None, "hp": None},
    {"name": "Rift Brood", "exp": 1600, "hp": 2950},
    {"name": "Rift Fragment", "exp": None, "hp": None},
    {"name": "Rift Invader", "exp": None, "hp": 6250},
    {"name": "Rift Lord", "exp": None, "hp": None},
    {"name": "Rift Minion", "exp": None, "hp": None},
    {"name": "Rift Phantom", "exp": None, "hp": None},
    {"name": "Rift Scythe", "exp": 2000, "hp": 3600},
    {"name": "Rift Spawn", "exp": None, "hp": None},
    {"name": "Rift Worm", "exp": 1195, "hp": 2800},
    {"name": "Ripper Spectre", "exp": 3500, "hp": 3800},
    {"name": "Risen Soldier", "exp": 0, "hp": 6000},
    {"name": "Roaring Lion", "exp": 800, "hp": 1000},
    {"name": "Roaring Water Elemental", "exp": 1300, "hp": 1750},
    {"name": "Roast Pork", "exp": 280, "hp": 420},
    {"name": "Robby the Reckless", "exp": 110, "hp": 155},
    {"name": "Rocko", "exp": 3400, "hp": 10000},
    {"name": "Rocky", "exp": 190, "hp": 390},
    {"name": "Ron the Ripper", "exp": 500, "hp": 1500},
    {"name": "Rorc", "exp": 105, "hp": 260},
    {"name": "Rot Elemental", "exp": 750, "hp": 850},
    {"name": "Rotspit", "exp": None, "hp": 6800},
    {"name": "Rotten Golem", "exp": 19000, "hp": 28000},
    {"name": "Rottie the Rotworm", "exp": 40, "hp": 65},
    {"name": "Rotworm", "exp": 40, "hp": 65},
    {"name": "Rotworm Queen", "exp": 75, "hp": 105},
    {"name": "Rukor Zad", "exp": 380, "hp": 380},
    {"name": "Running Elite Orc Guard", "exp": 0, "hp": None},
    {"name": "Rupture", "exp": None, "hp": 290000},
    {"name": "Rustheap Golem", "exp": 2100, "hp": 2800},
    {"name": "Sacred Snake", "exp": 0, "hp": 10},
    {"name": "Sacred Spider", "exp": 330, "hp": 550},
    {"name": "Salamander", "exp": 25, "hp": 70},
    {"name": "Salamander Trainer", "exp": 70, "hp": 220},
    {"name": "Samael", "exp": None, "hp": None},
    {"name": "Sand Brood", "exp": None, "hp": 2100},
    {"name": "Sand Vortex", "exp": None, "hp": None},
    {"name": "Sandcrawler", "exp": 20, "hp": 30},
    {"name": "Sandstone Scorpion", "exp": 680, "hp": 900},
    {"name": "Scar Tribe Shaman", "exp": 85, "hp": 115},
    {"name": "Scar Tribe Warrior", "exp": 85, "hp": 125},
    {"name": "Scarab", "exp": 120, "hp": 320},
    {"name": "Scarlett Etzel", "exp": 550, "hp": 30000},
    {"name": "Schiach", "exp": 580, "hp": 600},
    {"name": "Scissorion", "exp": 0, "hp": 0},
    {"name": "Scorn of the Emperor", "exp": 450, "hp": 45000},
    {"name": "Scorpion", "exp": 45, "hp": 45},
    {"name": "Sea Serpent", "exp": 2300, "hp": 1950},
    {"name": "Seacrest Serpent", "exp": 2600, "hp": 3000},
    {"name": "Seagull", "exp": 0, "hp": 25},
    {"name": "Security Golem", "exp": 0, "hp": None},
    {"name": "Serpent Spawn", "exp": 3050, "hp": 3000},
    {"name": "Servant Golem", "exp": 5, "hp": 1400},
    {"name": "Servant of Tentugly", "exp": None, "hp": None},
    {"name": "Shaburak Demon", "exp": 900, "hp": 1500},
    {"name": "Shaburak Lord", "exp": 1200, "hp": 2100},
    {"name": "Shaburak Prince", "exp": 1700, "hp": 2600},
    {"name": "Shadow Fiend", "exp": None, "hp": None},
    {"name": "Shadow Hound", "exp": 600, "hp": 555},
    {"name": "Shadow of Boreth", "exp": None, "hp": 600},
    {"name": "Shadow of Lersatio", "exp": None, "hp": 600},
    {"name": "Shadow of Marziel", "exp": None, "hp": 600},
    {"name": "Shadow Pupil", "exp": 410, "hp": 450},
    {"name": "Shadow Tentacle", "exp": None, "hp": None},
    {"name": "Shadowpelt", "exp": 4600, "hp": 6000},
    {"name": "Shadowstalker", "exp": 4000, "hp": 6100},
    {"name": "Shaper Matriarch", "exp": 1650, "hp": 2000},
    {"name": "Shard of Corruption", "exp": 5, "hp": 600},
    {"name": "Shard of Magnor", "exp": 0, "hp": None},
    {"name": "Shardhead", "exp": 650, "hp": 800},
    {"name": "Shark", "exp": 700, "hp": 1200},
    {"name": "Sharpclaw", "exp": 3000, "hp": 3300},
    {"name": "Sharptooth", "exp": 1600, "hp": 3100},
    {"name": "Sheep", "exp": 0, "hp": 20},
    {"name": "Shimmying Butterfly", "exp": 0, "hp": 20},
    {"name": "Ship Core", "exp": 0, "hp": None},
    {"name": "Shiversleep", "exp": 1900, "hp": 4600},
    {"name": "Shlorg", "exp": None, "hp": None},
    {"name": "Shock Head", "exp": 2300, "hp": 4200},
    {"name": "Shredderthrower", "exp": None, "hp": None},
    {"name": "Shulgrax", "exp": 50000, "hp": 290000},
    {"name": "Sibang", "exp": 105, "hp": 225},
    {"name": "Sight of Surrender", "exp": 17000, "hp": 28000},
    {"name": "Silencer", "exp": 5100, "hp": 5400},
    {"name": "Silver Rabbit", "exp": 0, "hp": 15},
    {"name": "Sin Devourer", "exp": None, "hp": None},
    {"name": "Sir Baeloc", "exp": 55000, "hp": None},
    {"name": "Sir Nictros", "exp": 55000, "hp": None},
    {"name": "Sir Valorcrest", "exp": 1800, "hp": 1600},
    {"name": "Siramal", "exp": 35000, "hp": 100000},
    {"name": "Sister Hetai", "exp": 20500, "hp": 25000},
    {"name": "Skeleton", "exp": 35, "hp": 50},
    {"name": "Skeleton Elite Warrior", "exp": 4500, "hp": 7800},
    {"name": "Skeleton Warrior", "exp": 45, "hp": 65},
    {"name": "Skunk", "exp": 3, "hp": 20},
    {"name": "Slick Water Elemental", "exp": 450, "hp": 550},
    {"name": "Slim", "exp": 580, "hp": 1025},
    {"name": "Slime", "exp": 160, "hp": 150},
    {"name": "Slime Puddle", "exp": None, "hp": None},
    {"name": "Slippery Northern Pike", "exp": 0, "hp": 100},
    {"name": "Sloth Wraith", "exp": None, "hp": None},
    {"name": "Slowing Slime", "exp": None, "hp": None},
    {"name": "Slug", "exp": 70, "hp": 255},
    {"name": "Smuggler", "exp": 48, "hp": 130},
    {"name": "Smuggler Baron Silvertoe", "exp": 170, "hp": 280},
    {"name": "Snail Slime", "exp": 0, "hp": None},
    {"name": "Snake", "exp": 10, "hp": 15},
    {"name": "Snake God Essence", "exp": 7410, "hp": 65000},
    {"name": "Snake Thing", "exp": None, "hp": 70000},
    {"name": "Solid Frozen Horror", "exp": None, "hp": None},
    {"name": "Somewhat Beatable Dragon", "exp": 0, "hp": None},
    {"name": "Son of Verminor", "exp": 5900, "hp": 8500},
    {"name": "Sorcerer Familiar", "exp": None, "hp": 20000},
    {"name": "Sorcerer's Apparition", "exp": 18870, "hp": 25000},
    {"name": "Soul of Dragonking Zyrtarch", "exp": None, "hp": None},
    {"name": "Soul Reaper", "exp": None, "hp": None},
    {"name": "Soul Scourge", "exp": 0, "hp": None},
    {"name": "Soul Spark", "exp": 0, "hp": 115},
    {"name": "Soul Sphere", "exp": None, "hp": None},
    {"name": "Soul-Broken Harbinger", "exp": 5800, "hp": 6300},
    {"name": "Soulcatcher", "exp": None, "hp": None},
    {"name": "Souleater", "exp": 1300, "hp": 1100},
    {"name": "Soulless Minion", "exp": None, "hp": None},
    {"name": "Soulsnatcher", "exp": None, "hp": None},
    {"name": "Spark of Destruction", "exp": None, "hp": 3900},
    {"name": "Sparkion", "exp": 1520, "hp": 2700},
    {"name": "Spawn of Despair", "exp": 2550, "hp": 35000},
    {"name": "Spawn of Devovorga", "exp": None, "hp": None},
    {"name": "Spawn of Havoc", "exp": None, "hp": None},
    {"name": "Spawn of the Schnitzel", "exp": 0, "hp": None},
    {"name": "Spawn of the Welter", "exp": None, "hp": None},
    {"name": "Spectral Scum", "exp": None, "hp": None},
    {"name": "Spectre", "exp": 2100, "hp": 1350},
    {"name": "Sphere of Wrath", "exp": None, "hp": None},
    {"name": "Sphinx", "exp": 7500, "hp": 8500},
    {"name": "Spider", "exp": 12, "hp": 20},
    {"name": "Spider Queen", "exp": 120, "hp": 10000},
    {"name": "Spidris", "exp": 2600, "hp": 3700},
    {"name": "Spidris Elite", "exp": 4000, "hp": 5000},
    {"name": "Spiky Carnivor", "exp": 1650, "hp": 2800},
    {"name": "Spirit of Earth", "exp": 800, "hp": 1200},
    {"name": "Spirit of Fertility", "exp": None, "hp": None},
    {"name": "Spirit of Fire", "exp": 950, "hp": 2210},
    {"name": "Spirit of Light", "exp": None, "hp": None},
    {"name": "Spirit of Water", "exp": 850, "hp": 1400},
    {"name": "Spit Nettle", "exp": 20, "hp": 150},
    {"name": "Spite of the Emperor", "exp": None, "hp": 48000},
    {"name": "Spiteful Spitter", "exp": None, "hp": None},
    {"name": "Spitter", "exp": 1100, "hp": 1500},
    {"name": "Splasher", "exp": 500, "hp": 1700},
    {"name": "Spy Rat", "exp": None, "hp": None},
    {"name": "Spyrat", "exp": 2500, "hp": 3000},
    {"name": "Spyrat", "exp": 2500, "hp": 3000},
    {"name": "Spyrat", "exp": 2500, "hp": 3000},
    {"name": "Spyrat", "exp": 2500, "hp": 3000},
    {"name": "Squid Warden", "exp": 15300, "hp": 16500},
    {"name": "Squidgy Slime", "exp": 55, "hp": 150},
    {"name": "Squire of Nictros", "exp": 0, "hp": None},
    {"name": "Squirrel", "exp": 0, "hp": 20},
    {"name": "Srezz Yellow Eyes", "exp": 4800, "hp": 6200},
    {"name": "Stabilizing Dread Intruder", "exp": 1900, "hp": 2800},
    {"name": "Stabilizing Reality Reaver", "exp": 1950, "hp": 2500},
    {"name": "Stalker", "exp": 90, "hp": 120},
    {"name": "Stampor", "exp": 780, "hp": 1200},
    {"name": "Starving Wolf", "exp": 65, "hp": 85},
    {"name": "Stolen Knowledge of Armor", "exp": 0, "hp": None},
    {"name": "Stolen Knowledge of Healing", "exp": 0, "hp": None},
    {"name": "Stolen Knowledge of Lifesteal", "exp": 0, "hp": None},
    {"name": "Stolen Knowledge of Spells", "exp": 0, "hp": None},
    {"name": "Stolen Knowledge of Summoning", "exp": 0, "hp": None},
    {"name": "Stolen Soul", "exp": None, "hp": None},
    {"name": "Stolen Tome of Portals", "exp": 0, "hp": None},
    {"name": "Stone Devourer", "exp": 2900, "hp": 4200},
    {"name": "Stone Golem", "exp": 160, "hp": 270},
    {"name": "Stone Rhino", "exp": 1800, "hp": 3000},
    {"name": "Stonecracker", "exp": 3500, "hp": 6500},
    {"name": "Stonerefiner", "exp": 500, "hp": 800},
    {"name": "Strange Rat", "exp": None, "hp": None},
    {"name": "Strange Slime", "exp": 0, "hp": 15},
    {"name": "Streaked Devourer", "exp": 6300, "hp": 7000},
    {"name": "Strong Glooth Horror", "exp": None, "hp": 20000},
    {"name": "Strong Soul", "exp": None, "hp": None},
    {"name": "Sulphur Scuttler", "exp": 900, "hp": 1300},
    {"name": "Sun-Marked Goanna", "exp": 7600, "hp": 7800},
    {"name": "Supercharged Mazzinor", "exp": None, "hp": None},
    {"name": "Superior Death Minion", "exp": 0, "hp": None},
    {"name": "Svoren the Mad", "exp": 3000, "hp": 6310},
    {"name": "Swamp Troll", "exp": 25, "hp": 55},
    {"name": "Swampling", "exp": 45, "hp": 80},
    {"name": "Swan Maiden", "exp": 700, "hp": 800},
    {"name": "Swarmer", "exp": 350, "hp": 460},
    {"name": "Swarmer Hatchling", "exp": 0, "hp": 5},
    {"name": "Sword of Vengeance", "exp": None, "hp": None},
    {"name": "Symbol of Fear", "exp": None, "hp": None},
    {"name": "Symbol of Hatred", "exp": None, "hp": None},
    {"name": "Tainted Soul", "exp": 0, "hp": 250},
    {"name": "Tainted Soul Splinter", "exp": 0, "hp": None},
    {"name": "Tanjis", "exp": 15000, "hp": 30000},
    {"name": "Tarantula", "exp": 120, "hp": 225},
    {"name": "Tarbaz", "exp": 55000, "hp": None},
    {"name": "Tarnished Spirit", "exp": 120, "hp": 150},
    {"name": "Tazhadur", "exp": 9000, "hp": 10000},
    {"name": "Teleskor", "exp": 70, "hp": 80},
    {"name": "Teneshpar", "exp": 20000, "hp": 15000},
    {"name": "Tentacle", "exp": 0, "hp": 2500},
    {"name": "Tentacle of the Deep Terror", "exp": None, "hp": None},
    {"name": "Tentugly's Head", "exp": 40000, "hp": None},
    {"name": "Terofar", "exp": 24000, "hp": 40000},
    {"name": "Terramite", "exp": 160, "hp": 365},
    {"name": "Terrified Elephant", "exp": 160, "hp": 320},
    {"name": "Terror Bird", "exp": 150, "hp": 300},
    {"name": "Terrorsleep", "exp": 6900, "hp": 7200},
    {"name": "Thaian", "exp": None, "hp": None},
    {"name": "Thaian's Ghost", "exp": None, "hp": None},
    {"name": "Thalas", "exp": 2950, "hp": 4100},
    {"name": "Thanatursus", "exp": 6300, "hp": 7200},
    {"name": "Thawing Dragon Lord", "exp": 2100, "hp": 25000},
    {"name": "The Abomination", "exp": None, "hp": None},
    {"name": "The Armored Voidborn", "exp": None, "hp": None},
    {"name": "The Astral Source", "exp": None, "hp": None},
    {"name": "The Axeorcist", "exp": 3000, "hp": 5100},
    {"name": "The Baron from Below", "exp": None, "hp": None},
    {"name": "The Big Bad One", "exp": 170, "hp": 300},
    {"name": "The Blazing Rose", "exp": None, "hp": None},
    {"name": "The Blazing Time Guardian", "exp": 50000, "hp": None},
    {"name": "The Blightfather", "exp": 400, "hp": 400},
    {"name": "The Bloodtusk", "exp": 300, "hp": 600},
    {"name": "The Bloodweb", "exp": 1450, "hp": 1750},
    {"name": "The Book of Death", "exp": 0, "hp": 7800},
    {"name": "The Book of Secrets", "exp": None, "hp": None},
    {"name": "The Brainstealer", "exp": None, "hp": None},
    {"name": "The Cold of Winter", "exp": 0, "hp": None},
    {"name": "The Collector", "exp": 100, "hp": 340},
    {"name": "The Corruptor of Souls", "exp": None, "hp": None},
    {"name": "The Count", "exp": 450, "hp": 1250},
    {"name": "The Count of the Core", "exp": None, "hp": None},
    {"name": "The Dark Dancer", "exp": 435, "hp": 805},
    {"name": "The Destruction", "exp": None, "hp": None},
    {"name": "The Devourer of Secrets", "exp": None, "hp": None},
    {"name": "The Diamond Blossom", "exp": 10000, "hp": None},
    {"name": "The Distorted Astral Source", "exp": None, "hp": None},
    {"name": "The Dread Maiden", "exp": None, "hp": None},
    {"name": "The Dreadorian", "exp": 4000, "hp": 9000},
    {"name": "The Duke of the Depths", "exp": None, "hp": None},
    {"name": "The Enraged Thorn Knight", "exp": 30000, "hp": None},
    {"name": "The Evil Eye", "exp": 750, "hp": 1200},
    {"name": "The False God", "exp": 50000, "hp": None},
    {"name": "The Fear Feaster", "exp": None, "hp": None},
    {"name": "The Fettered Shatterer", "exp": None, "hp": None},
    {"name": "The Fire Empowered Duke", "exp": None, "hp": None},
    {"name": "The First Dragon", "exp": None, "hp": None},
    {"name": "The Flaming Orchid", "exp": 8500, "hp": 4000},
    {"name": "The Freezing Time Guardian", "exp": 50000, "hp": None},
    {"name": "The Frog Prince", "exp": 1, "hp": 55},
    {"name": "The Great Schnitzel", "exp": 0, "hp": None},
    {"name": "The Hag", "exp": 510, "hp": 935},
    {"name": "The Hairy One", "exp": 115, "hp": 325},
    {"name": "The Halloween Hare", "exp": 0, "hp": 2000},
    {"name": "The Handmaiden", "exp": 7500, "hp": 19500},
    {"name": "The Heat of Summer", "exp": 0, "hp": None},
    {"name": "The Horned Fox", "exp": 300, "hp": 265},
    {"name": "The Hunger", "exp": None, "hp": None},
    {"name": "The Hungerer", "exp": None, "hp": None},
    {"name": "The Hungry Baron from Below", "exp": None, "hp": None},
    {"name": "The Imperor", "exp": 8000, "hp": 15000},
    {"name": "The Keeper", "exp": 3205, "hp": 40000},
    {"name": "The Last Lore Keeper", "exp": None, "hp": None},
    {"name": "The Lily of Night", "exp": None, "hp": None},
    {"name": "The Lord of the Lice", "exp": None, "hp": None},
    {"name": "The Manhunter", "exp": 3000, "hp": 4500},
    {"name": "The Many", "exp": 4000, "hp": 5000},
    {"name": "The Masked Marauder", "exp": 3500, "hp": 7320},
    {"name": "The Mean Masher", "exp": None, "hp": None},
    {"name": "The Mega Magmaoid", "exp": 80000, "hp": None},
    {"name": "The Mutated Pumpkin", "exp": 30000, "hp": 500000},
    {"name": "The Nightmare Beast", "exp": 255000, "hp": None},
    {"name": "The Noxious Spawn", "exp": 6000, "hp": 9500},
    {"name": "The Obliverator", "exp": 6000, "hp": 9020},
    {"name": "The Old Whopper", "exp": 750, "hp": 785},
    {"name": "The Old Widow", "exp": 4200, "hp": 3200},
    {"name": "The Pale Count", "exp": 28000, "hp": 50000},
    {"name": "The Pale Worm", "exp": None, "hp": None},
    {"name": "The Percht Queen", "exp": 500, "hp": 2300},
    {"name": "The Pit Lord", "exp": 2500, "hp": 5270},
    {"name": "The Plasmother", "exp": 12000, "hp": 7500},
    {"name": "The Rage", "exp": None, "hp": None},
    {"name": "The Ravager", "exp": 14980, "hp": 53500},
    {"name": "The Red Knight", "exp": 0, "hp": None},
    {"name": "The Remorseless Corruptor", "exp": None, "hp": None},
    {"name": "The Sandking", "exp": None, "hp": None},
    {"name": "The Scion of Havoc", "exp": None, "hp": None},
    {"name": "The Scourge of Oblivion", "exp": 75000, "hp": None},
    {"name": "The Shatterer", "exp": None, "hp": None},
    {"name": "The Shielded Thorn Knight", "exp": None, "hp": None},
    {"name": "The Sinister Hermit", "exp": 0, "hp": None},
    {"name": "The Snapper", "exp": 150, "hp": 300},
    {"name": "The Souldespoiler", "exp": 50000, "hp": 290000},
    {"name": "The Source of Corruption", "exp": None, "hp": None},
    {"name": "The Spellstealer", "exp": None, "hp": None},
    {"name": "The Time Guardian", "exp": 50000, "hp": None},
    {"name": "The Unarmored Voidborn", "exp": 15000, "hp": 250000},
    {"name": "The Unwelcome", "exp": None, "hp": None},
    {"name": "The Voice of Ruin", "exp": 3500, "hp": 5500},
    {"name": "The Weakened Count", "exp": 450, "hp": 740},
    {"name": "The Welter", "exp": 11000, "hp": 25000},
    {"name": "Thief", "exp": 5, "hp": 60},
    {"name": "Thieving Squirrel", "exp": 15, "hp": 55},
    {"name": "Thorn Minion", "exp": None, "hp": None},
    {"name": "Thornback Tortoise", "exp": 150, "hp": 300},
    {"name": "Thornfire Wolf", "exp": 200, "hp": 600},
    {"name": "Thul", "exp": 2700, "hp": 2950},
    {"name": "Tiger", "exp": 40, "hp": 75},
    {"name": "Time Keeper", "exp": None, "hp": None},
    {"name": "Time Waster", "exp": None, "hp": None},
    {"name": "Tiquandas Revenge", "exp": 2635, "hp": 1800},
    {"name": "Tirecz", "exp": 6000, "hp": 25000},
    {"name": "Toad", "exp": 60, "hp": 135},
    {"name": "Tomb Servant", "exp": 215, "hp": 475},
    {"name": "Tormented Ghost", "exp": 5, "hp": 210},
    {"name": "Tormentor", "exp": 3200, "hp": 4100},
    {"name": "Tortoise", "exp": 90, "hp": 185},
    {"name": "Travelling Merchant", "exp": 65, "hp": 100},
    {"name": "Tremendous Tyrant", "exp": 6100, "hp": 11500},
    {"name": "Tremor Worm", "exp": None, "hp": 125000},
    {"name": "Tremorak", "exp": 1300, "hp": 10000},
    {"name": "Troll", "exp": 20, "hp": 50},
    {"name": "Troll Champion", "exp": 40, "hp": 75},
    {"name": "Troll Guard", "exp": 25, "hp": 60},
    {"name": "Troll Legionnaire", "exp": 140, "hp": 210},
    {"name": "Troll Marauder", "exp": 40, "hp": 70},
    {"name": "Troll-Trained Salamander", "exp": 23, "hp": 70},
    {"name": "Tromphonyte", "exp": 1300, "hp": 3000},
    {"name": "True Dawnfire Asura", "exp": 7475, "hp": 8500},
    {"name": "True Frost Flower Asura", "exp": 7069, "hp": 4000},
    {"name": "True Midnight Asura", "exp": 7313, "hp": 9000},
    {"name": "Tunnel Tyrant", "exp": 3400, "hp": 5200},
    {"name": "Turbulent Elemental", "exp": 19360, "hp": 28000},
    {"name": "Twisted Pooka", "exp": 600, "hp": 700},
    {"name": "Twisted Shaper", "exp": 1750, "hp": 2500},
    {"name": "Tyrn", "exp": 6900, "hp": 12000},
    {"name": "Tzumrah the Dazzler", "exp": 1700, "hp": 1700},
    {"name": "Ugly Monster", "exp": 1000, "hp": 10000},
    {"name": "Unaz the Mean", "exp": 22000, "hp": 28000},
    {"name": "Unbeatable Dragon", "exp": 0, "hp": None},
    {"name": "Unbound Blightwalker", "exp": None, "hp": None},
    {"name": "Unbound Defiler", "exp": None, "hp": None},
    {"name": "Unbound Demon", "exp": None, "hp": None},
    {"name": "Unbound Demon Outcast", "exp": None, "hp": None},
    {"name": "Undead Cavebear", "exp": 600, "hp": 450},
    {"name": "Undead Dragon", "exp": 7200, "hp": 8350},
    {"name": "Undead Elite Gladiator", "exp": 4740, "hp": 8000},
    {"name": "Undead Gladiator", "exp": 800, "hp": 1000},
    {"name": "Undead Jester", "exp": 5, "hp": 355},
    {"name": "Undead Mine Worker", "exp": 45, "hp": 65},
    {"name": "Undead Prospector", "exp": 85, "hp": 100},
    {"name": "Ungreez", "exp": 500, "hp": 8200},
    {"name": "Unleashed Hex", "exp": 0, "hp": None},
    {"name": "Unpleasant Dream", "exp": 0, "hp": None},
    {"name": "Unstable Spark", "exp": 1500, "hp": 10500},
    {"name": "Unstable Tunnel", "exp": None, "hp": None},
    {"name": "Urmahlullu the Immaculate", "exp": None, "hp": None},
    {"name": "Urmahlullu the Tamed", "exp": None, "hp": None},
    {"name": "Urmahlullu the Weakened", "exp": None, "hp": None},
    {"name": "Used Food Wagon", "exp": None, "hp": None},
    {"name": "Ushuriel", "exp": 10000, "hp": 31500},
    {"name": "Usurper Archer", "exp": 6800, "hp": 7300},
    {"name": "Usurper Commander", "exp": 7200, "hp": 8500},
    {"name": "Usurper Knight", "exp": 6900, "hp": 8200},
    {"name": "Usurper Warlock", "exp": 7000, "hp": 7500},
    {"name": "Utua Stone Sting", "exp": 5100, "hp": 6400},
    {"name": "Valkyrie", "exp": 85, "hp": 190},
    {"name": "Vampire", "exp": 305, "hp": 475},
    {"name": "Vampire Bride", "exp": 1050, "hp": 1200},
    {"name": "Vampire Pig", "exp": 165, "hp": 305},
    {"name": "Vampire Viscount", "exp": 800, "hp": 1200},
    {"name": "Vampiric Blood", "exp": 0, "hp": 3500},
    {"name": "Varnished Diremaw", "exp": 5900, "hp": 9000},
    {"name": "Vashresamun", "exp": 2950, "hp": 4000},
    {"name": "Venerable Girtablilu", "exp": 5300, "hp": 8500},
    {"name": "Vermin Swarm", "exp": None, "hp": None},
    {"name": "Versperoth", "exp": 30000, "hp": 100000},
    {"name": "Vexclaw", "exp": 6248, "hp": 8500},
    {"name": "Vibrant Phantom", "exp": 19700, "hp": 27000},
    {"name": "Vicious Manbat", "exp": 1200, "hp": 1700},
    {"name": "Vicious Squire", "exp": 900, "hp": 1000},
    {"name": "Vile Grandmaster", "exp": 1500, "hp": 1700},
    {"name": "Voidshard", "exp": 0, "hp": None},
    {"name": "Vok the Freakish", "exp": 27000, "hp": 32000},
    {"name": "Vortex Spawn", "exp": 0, "hp": 500},
    {"name": "Vulcongra", "exp": 1100, "hp": 1600},
    {"name": "Vulnerable Cocoon", "exp": None, "hp": 200000},
    {"name": "Wailing Widow", "exp": 450, "hp": 850},
    {"name": "Walker", "exp": 2200, "hp": 3000},
    {"name": "Wandering Prospector", "exp": None, "hp": None},
    {"name": "War Golem", "exp": 2310, "hp": 4300},
    {"name": "War Servant", "exp": None, "hp": None},
    {"name": "War Wolf", "exp": 55, "hp": 140},
    {"name": "Warlock", "exp": 4000, "hp": 3500},
    {"name": "Warlord Ruzad", "exp": 1700, "hp": 1500},
    {"name": "Warm Fire", "exp": None, "hp": None},
    {"name": "Wasp", "exp": 24, "hp": 35},
    {"name": "Waspoid", "exp": 830, "hp": 1100},
    {"name": "Water Buffalo", "exp": 20, "hp": 390},
    {"name": "Water Elemental", "exp": 650, "hp": 550},
    {"name": "Weak Soul", "exp": None, "hp": None},
    {"name": "Weakened Demon", "exp": 0, "hp": 5},
    {"name": "Weakened Frazzlemaw", "exp": 1000, "hp": 1200},
    {"name": "Weakened Glooth Horror", "exp": 245, "hp": 10000},
    {"name": "Weakened Shlorg", "exp": 6500, "hp": 10000},
    {"name": "Webster", "exp": 1200, "hp": 2950},
    {"name": "Weeper", "exp": 4800, "hp": 6800},
    {"name": "Weeping Soul", "exp": None, "hp": None},
    {"name": "Werebadger", "exp": 1600, "hp": 1700},
    {"name": "Werebear", "exp": 2100, "hp": 2400},
    {"name": "Wereboar", "exp": 2000, "hp": 2200},
    {"name": "Werefox", "exp": 1600, "hp": 1500},
    {"name": "Werehyaena", "exp": 2200, "hp": 2700},
    {"name": "Werehyaena Shaman", "exp": 2200, "hp": 2500},
    {"name": "Werelion", "exp": 2400, "hp": 2800},
    {"name": "Werelioness", "exp": 2500, "hp": 3000},
    {"name": "Werewolf", "exp": 1900, "hp": 1955},
    {"name": "Whirling Blades", "exp": 0, "hp": None},
    {"name": "White Deer", "exp": 0, "hp": 195},
    {"name": "White Lion", "exp": 2300, "hp": 2700},
    {"name": "White Pale", "exp": 390, "hp": 500},
    {"name": "White Shade", "exp": 120, "hp": 260},
    {"name": "Wiggler", "exp": 900, "hp": 1200},
    {"name": "Wild Dog", "exp": 0, "hp": 20},
    {"name": "Wild Fire Magic", "exp": None, "hp": None},
    {"name": "Wild Fury Magic", "exp": None, "hp": None},
    {"name": "Wild Horse", "exp": 0, "hp": 75},
    {"name": "Wild Knowledge", "exp": 0, "hp": None},
    {"name": "Wild Nature Magic", "exp": None, "hp": None},
    {"name": "Wild Warrior", "exp": 60, "hp": 135},
    {"name": "Wild Water Magic", "exp": None, "hp": None},
    {"name": "Wildness of Urmahlullu", "exp": None, "hp": None},
    {"name": "Willi Wasp", "exp": 250, "hp": 250},
    {"name": "Wilting Leaf Golem", "exp": 145, "hp": 380},
    {"name": "Wine Cask", "exp": 0, "hp": None},
    {"name": "Winter Wolf", "exp": 20, "hp": 30},
    {"name": "Wisdom of Urmahlullu", "exp": None, "hp": None},
    {"name": "Wisp", "exp": 0, "hp": 115},
    {"name": "Witch", "exp": 120, "hp": 300},
    {"name": "Wolf", "exp": 18, "hp": 25},
    {"name": "Woodling", "exp": 40, "hp": 80},
    {"name": "Worker Golem", "exp": 1250, "hp": 1470},
    {"name": "World Devourer", "exp": None, "hp": None},
    {"name": "Worm Priestess", "exp": 1500, "hp": 1100},
    {"name": "Wormling", "exp": None, "hp": None},
    {"name": "Wounded Cave Draptor", "exp": 50, "hp": 5},
    {"name": "Wrath of the Emperor", "exp": 600, "hp": 55000},
    {"name": "Wyrm", "exp": 1550, "hp": 1825},
    {"name": "Wyvern", "exp": 515, "hp": 795},
    {"name": "Xenia", "exp": 255, "hp": 200},
    {"name": "Xogixath", "exp": 22000, "hp": None},
    {"name": "Yaga the Crone", "exp": 375, "hp": 620},
    {"name": "Yakchal", "exp": 4400, "hp": 5750},
    {"name": "Yalahari", "exp": 5, "hp": 150},
    {"name": "Yalahari Despoiler", "exp": None, "hp": None},
    {"name": "Yeti", "exp": 460, "hp": 950},
    {"name": "Yielothax", "exp": 1250, "hp": 1500},
    {"name": "Yirkas Blue Scales", "exp": 4900, "hp": 6300},
    {"name": "Young Goanna", "exp": 6100, "hp": 6200},
    {"name": "Young Sea Serpent", "exp": 1000, "hp": 1050},
    {"name": "Young Troll", "exp": 12, "hp": 30},
    {"name": "Zamulosh", "exp": 50000, "hp": None},
    {"name": "Zanakeph", "exp": 9900, "hp": 13000},
    {"name": "Zarabustor", "exp": 8000, "hp": 5100},
    {"name": "Zarcorix of Yalahar", "exp": None, "hp": None},
    {"name": "Zavarash", "exp": 21000, "hp": 35000},
    {"name": "Zevelon Duskbringer", "exp": 1800, "hp": 1400},
    {"name": "Zomba", "exp": 300, "hp": 300},
    {"name": "Zombie", "exp": 280, "hp": 500},
    {"name": "Zorvorax", "exp": 9000, "hp": 10000},
    {"name": "Zugurosh", "exp": 10000, "hp": 90500},
    {"name": "Zulazza the Corruptor", "exp": 10000, "hp": 46500},
    {"name": "Zushuka", "exp": 9000, "hp": 15000}
]
