rings = {
    'Axe Ring': {'minimumRequiredLevel': 0, 'vocation': 'all', 'arm': 0, 'durationInMinutes': 30, 'weight': 0.9},
    'Blister Ring': {'minimumRequiredLevel': 220, 'vocation': 'all', 'arm': 0, 'durationInMinutes': None, 'weight': 0.9},
    'Broken Ring of Ending': {'minimumRequiredLevel': 0, 'vocation': 'all', 'arm': 0, 'durationInMinutes': None, 'weight': 0.6},
    'Broken Wedding Ring': {'minimumRequiredLevel': 0, 'vocation': 'all', 'arm': 0, 'durationInMinutes': None, 'weight': 0.4},
    'Butterfly Ring': {'minimumRequiredLevel': 50, 'vocation': 'all', 'arm': 2, 'durationInMinutes': None, 'weight': 1.20},
    'Charged Spiritthorn Ring': {'minimumRequiredLevel': 400, 'vocation': 'knight', 'arm': 2, 'durationInMinutes': 180, 'weight': 0.95},
    "Claw of 'The Noxious Spawn'": {'minimumRequiredLevel': 100, 'vocation': 'all', 'arm': 0, 'durationInMinutes': None, 'weight': 5},
    'Club Ring': {'minimumRequiredLevel': 0, 'vocation': 'all', 'arm': 0, 'durationInMinutes': 30, 'weight': 0.9},
    'Crystal Ring': {'minimumRequiredLevel': 0, 'vocation': 'all', 'arm': 0, 'durationInMinutes': None, 'weight': 0.90},
    'Death Ring': {'minimumRequiredLevel': 0, 'vocation': 'all', 'arm': 1, 'durationInMinutes': 7.5, 'weight': 0.8},
    'Dwarven Ring': {'minimumRequiredLevel': 0, 'vocation': 'all', 'arm': 0, 'durationInMinutes': 60, 'weight': 1.1},
    'Enchanted Blister Ring': {'minimumRequiredLevel': 220, 'vocation': 'all', 'arm': 0, 'durationInMinutes': 60, 'weight': 0.9},
    'Enchanted Ring of Souls': {'minimumRequiredLevel': 200, 'vocation': 'all', 'arm': 0, 'durationInMinutes': 120, 'weight': 0.8},
    'Energy Ring': {'minimumRequiredLevel': 0, 'vocation': 'knight/paladin', 'arm': 0, 'durationInMinutes': 10, 'weight': 0.8},
    'Engraved Wedding Ring': {'minimumRequiredLevel': 0, 'vocation': 'all', 'arm': 0, 'durationInMinutes': None, 'weight': 0.4},
    'Family Signet Ring': {'minimumRequiredLevel': 0, 'vocation': 'all', 'arm': 0, 'durationInMinutes': None, 'weight': 0.8},
    'Frozen Claw': {'minimumRequiredLevel': 0, 'vocation': 'all', 'arm': 0, 'durationInMinutes': None, 'weight': 4.55},
    'Gold Ring': {'minimumRequiredLevel': 0, 'vocation': 'all', 'arm': 0, 'durationInMinutes': None, 'weight': 1},
    'Horn Ring': {'minimumRequiredLevel': 0, 'vocation': 'all', 'arm': 1, 'durationInMinutes': None, 'weight': 1.2},
    'Life Ring': {'minimumRequiredLevel': 0, 'vocation': 'all', 'arm': 0, 'durationInMinutes': 20, 'weight': 0.8},
    'Lion Ring': {'minimumRequiredLevel': 0, 'vocation': 'all', 'arm': 0, 'durationInMinutes': None, 'weight': 0.4},
    'Might Ring': {'minimumRequiredLevel': 0, 'vocation': 'all', 'arm': 0, 'durationInMinutes': None, 'weight': 1},
    'Power Ring': {'minimumRequiredLevel': 0, 'vocation': 'all', 'arm': 0, 'durationInMinutes': 30, 'weight': 0.8},
    'Prismatic Ring': {'minimumRequiredLevel': 120, 'vocation': 'all', 'arm': 0, 'durationInMinutes': 60, 'weight': 1.05},
    "Rerun's Ring": {'minimumRequiredLevel': 0, 'vocation': 'all', 'arm': 0, 'durationInMinutes': None, 'weight': 0.9},
    'Ring of Ending': {'minimumRequiredLevel': 200, 'vocation': 'all', 'arm': 0, 'durationInMinutes': None, 'weight': 0},
    'Ring of Healing': {'minimumRequiredLevel': 0, 'vocation': 'all', 'arm': 0, 'durationInMinutes': 7.5, 'weight': 0.8},
    'Ring of Red Plasma': {'minimumRequiredLevel': 100, 'vocation': 'knight', 'arm': 0, 'durationInMinutes': 30, 'weight': 0.9},
    'Ring of Secret Thoughts': {'minimumRequiredLevel': 0, 'vocation': 'all', 'arm': 0, 'durationInMinutes': None, 'weight': 0.9},
    'Ring of Souls': {'minimumRequiredLevel': 200, 'vocation': 'all', 'arm': 0, 'durationInMinutes': None, 'weight': 0.8},
    'Ring of the Sky': {'minimumRequiredLevel': 0, 'vocation': 'all', 'arm': 0, 'durationInMinutes': None, 'weight': 0.4},
    'Ring of Wishes': {'minimumRequiredLevel': 0, 'vocation': 'all', 'arm': 0, 'durationInMinutes': None, 'weight': 0.5},
    'Shapeshifter Ring': {'minimumRequiredLevel': 0, 'vocation': 'all', 'arm': 1, 'durationInMinutes': 600, 'weight': 0.8},
    'Signet Ring': {'minimumRequiredLevel': 0, 'vocation': 'all', 'arm': 0, 'durationInMinutes': None, 'weight': 0.8},
    'Spiritthorn Ring': {'minimumRequiredLevel': 400, 'vocation': 'knight', 'arm': 0, 'durationInMinutes': None, 'weight': 0.95},
    'Star Ring': {'minimumRequiredLevel': 0, 'vocation': 'noVocation', 'arm': 0, 'durationInMinutes': 10, 'weight': 0.8},
    'Stealth Ring': {'minimumRequiredLevel': 0, 'vocation': 'all', 'arm': 0, 'durationInMinutes': 10, 'weight': 1},
    'Suspicious Signet Ring': {'minimumRequiredLevel': 0, 'vocation': 'all', 'arm': 0, 'durationInMinutes': None, 'weight': 0.8},
    'Sweetheart Ring': {'minimumRequiredLevel': 0, 'vocation': 'all', 'arm': 0, 'durationInMinutes': None, 'weight': 0.9},
    'Sword Ring': {'minimumRequiredLevel': 0, 'vocation': 'all', 'arm': 0, 'durationInMinutes': 30, 'weight': 0.9},
    'Time Ring': {'minimumRequiredLevel': 0, 'vocation': 'all', 'arm': 0, 'durationInMinutes': 10, 'weight': 0.9},
    'Unstable Ring of Ending': {'minimumRequiredLevel': 0, 'vocation': 'all', 'arm': 0, 'durationInMinutes': None, 'weight': 0.6},
    "Vampire's Signet Ring": {'minimumRequiredLevel': 0, 'vocation': 'all', 'arm': 0, 'durationInMinutes': None, 'weight': 0.1},
    'Wedding Ring': {'minimumRequiredLevel': 0, 'vocation': 'all', 'arm': 0, 'durationInMinutes': None, 'weight': 0.4},
}
