spells = {
    'exana kor': {'manaNeeded': 30, 'cooldownInSeconds': 6},
    'exana pox': {'manaNeeded': 30, 'cooldownInSeconds': 6},
    'exani hur down': {'manaNeeded': 50, 'cooldownInSeconds': 2},
    'exani hur up': {'manaNeeded': 50, 'cooldownInSeconds': 2},
    'exani tera': {'manaNeeded': 20, 'cooldownInSeconds': 2},
    'exeta amp res': {'manaNeeded': 80, 'cooldownInSeconds': 2},
    'exeta res': {'manaNeeded': 40, 'cooldownInSeconds': 2},
    'exiva': {'manaNeeded': 20, 'cooldownInSeconds': 2},
    'exiva moe res': {'manaNeeded': 20, 'cooldownInSeconds': 2},
    'exori': {'manaNeeded': 115, 'cooldownInSeconds': 4},
    'exori gran': {'manaNeeded': 340, 'cooldownInSeconds': 6},
    'exori gran ico': {'manaNeeded': 300, 'cooldownInSeconds': 30},
    'exori ico': {'manaNeeded': 30, 'cooldownInSeconds': 6},
    'exori mas': {'manaNeeded': 160, 'cooldownInSeconds': 8},
    'exori min': {'manaNeeded': 200, 'cooldownInSeconds': 6},
    'exori hur': {'manaNeeded': 40, 'cooldownInSeconds': 6},
    'exura ico': {'manaNeeded': 40, 'cooldownInSeconds': 1},
    'exura infir ico': {'manaNeeded': 10, 'cooldownInSeconds': 1},
    'exura med ico': {'manaNeeded': 90, 'cooldownInSeconds': 1},
    'exura gran ico': {'manaNeeded': 200, 'cooldownInSeconds': 600},
    'utamo tempo': {'manaNeeded': 200, 'cooldownInSeconds': 2},
    'utani hur': {'manaNeeded': 60, 'cooldownInSeconds': 2},
    'utani tempo hur': {'manaNeeded': 100, 'cooldownInSeconds': 2},
    'utevo gran lux': {'manaNeeded': 60, 'cooldownInSeconds': 2},
    'utevo gran res eq': {'manaNeeded': 1000, 'cooldownInSeconds': 1800},
    'utevo lux': {'manaNeeded': 20, 'cooldownInSeconds': 2},
    'utito mas sio': {'manaNeeded': None, 'cooldownInSeconds': 2},
    'utito tempo': {'manaNeeded': 290, 'cooldownInSeconds': 2},
    'utori kor': {'manaNeeded': 30, 'cooldownInSeconds': 30},
    'utura': {'manaNeeded': 75, 'cooldownInSeconds': 60},
    'utura gran': {'manaNeeded': 165, 'cooldownInSeconds': 60},
}

healingSpells = ['exura infir ico', 'exura ico', 'exura med ico', 'exura gran ico', 'utura', 'utura gran']
